import json
from pathlib import Path
stage=json.loads(Path('.trellis/tasks/10-03-geo-408-api-acceptance/evidence/audit-stage-harness.json').read_text())['paths']
message='''实现 GEO-408 的独立真实栈测试装配，repo /Users/sc/PycharmProjects/partsignal。先读 AGENTS.md、backend/AGENTS.md、.trellis/spec/infra/e2e-isolation.md，current task .trellis/tasks/10-03-geo-408-api-acceptance/{prd,design}.md，408文档相关单元。你不独占仓库，保留他人修改；主代理拥有 frontend/tests/e2e 与frontend/src、docs/全部，不改这些。你的写所有权仅 backend/tests/geo_e2e_runtime.py、backend/tests/geo_e2e_provider.py（必要可拆同前缀文件）、backend/tests/unit/test_geo_e2e_runtime.py、deploy/scripts/e2e-local.sh、deploy/scripts/e2e-environment.py、deploy/scripts/e2e-geo.sh（如需要）、Makefile。不得改 backend/app 生产边界或schema/migration/contracts，不Git，不启动共享服务/端口，不运行full E2E（主代理集成后运行），目标单元测试及ruff可运行。
交付完整安全harness：默认原canonical模式保持，新增 PARTSIGNAL_E2E_GEO_MODE=enabled|api-disabled|monitoring-disabled，对应flags true/true、true/false、false/false；GEO phase默认SPEC frontend/tests/e2e/geo-api-real-stack.spec.ts。闭开关phase同spec通过env分支。PARTSIGNAL_E2E_GEO_PROVIDER_URL=http://127.0.0.1:19012；端口登记preflight/ready/cleanup，PID精确清理、secret scan现有机制复用。make e2e须依次运行原canonical、3geo modes、原fixture；外层可用e2e-geo.sh。每phase独占随机DB/Redis14并清理。
所有放宽只测试processfactory入口 tests.geo_e2e_runtime:app / :celery_app；必须启动时验证APP_ENV=test，精确随机partsignal_e2e_YYYYMMDD_hex32数据库及PostgreSQL owner comment一致 envowner token，非0Redis，确切127.0.0.1:19012/v1且无法外访真实平台。仅进程内批准openai-compatible-chat。严格虚构输入prompt为正则 GEO408 (SUCCESS|RATE_LIMIT|UNKNOWN|INTERNAL|BUDGET) UUID，以此及subjects canonical_name GEO408 前缀、无product绑定约束PUBLIC，仅INTERNAL仍INTERNAL。Production BatchInputs仍INTERNAL/defaultregistryapprovedfalse。使用真实Collector/transport且每次collector请求仅fake地址，内存X-GEO-Attempt-ID=真实Run UUID；Profile诊断注入TestReservation.attempt_id，模型诊断独立UUID，不持久化改渠道header。fake保留计数不去重，增加test-only/v1/models listing供UI model fetch（生产fake可继承handler）；真实模型diagnosis也调用相同fake。
测试场景配置由严格prompt在真实collect之前用loopback控制PUT生成；SUCCESS返回citations+partial_usage prompt7，completion/total null、reported_cost0.001200USD、websearchnull；RATE_LIMIT首次attempt429，retry后成功；UNKNOWN首次disconnect，retry成功；BUDGET测试estimate仅fake固定0.001200USD并budget0.000001，则零POST。不得自动重试，不吞错或伪造状态。场景控制必须有真实run attempt_no从CollectionRequest或PG只读获取。
关闭phase必须用已有ApplicationService生成真实PENDING API Run及真实Celery稳定ID排队，之后API/Worker启动对应关闭flags。测试前置图可在受控ownedDB中以明确test fixture创建基础配置并调用batchservice，不SQL强行改Run状态；图仅虚构数据、与用户UI流程分离。提供 PARTSIGNAL_E2E_GEO_FIXTURE_FILE=<JSON> 对frontend暴露 {run_id,batch_id,profile_id,diagnostic_attempt_id?}。API/Worker全关后UI仍读取历史；Worker结果FAILED/COLLECTOR_DISABLED/NOT_STARTED，fake run UUID count0，并API新增/重试明确拒绝。闭phase基础配置seed可在factory启用临时进程做，完成后全新关闭进程，无持久flag魔改；正常enabled phase图由主代理UI创建。不进入后续GEO任务。
复用现有database生命周期/secret canary/精确redis清理。保持源码单文件<500lines。提交中文最终总结、实际修改文件、验证命令结果、env/interface与残余风险；普通进度不发，只blocker/交付/影响父代理契约发消息。'''
d={'version':5,'plan_id':'geo408-harness','max_concurrent_workers':1,'runtime_workers':[],'prior_tasks':[],'tasks':[{'task_id':'geo_test_harness','task_name':'geo_test_harness','agent_type':'deep_engineer','attempt':1,'depends_on':[],'read_paths':['backend','deploy','.trellis/spec/infra'], 'write_paths':['backend/tests/geo_e2e_runtime.py','backend/tests/geo_e2e_provider.py','backend/tests/unit/test_geo_e2e_runtime.py','deploy/scripts/e2e-local.sh','deploy/scripts/e2e-environment.py','deploy/scripts/e2e-geo.sh','Makefile'],'independent_review':False,'review_of_task_ids':[],'reuse_worker_id':None,'accounting_scope':'not_available','dispatch_method':'spawn_agent','fork_turns':'none','delivery_mode':'complete_task','progress_policy':'blocker_or_final','deliverable':'安全隔离的GEO fake真实栈测试装配与三阶段开关验收入口','acceptance_criteria':['生产批准/分级/网络安全边界保持，所有装配仅test ownedDB loopback','测试模块目标检查通过并交付真实栈接线']} ]}
Path(stage['draft']).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
Path(stage['dispatch_dir']).mkdir(exist_ok=True)
Path(stage['dispatch_dir']+'/geo_test_harness.json').write_text(json.dumps({'task_name':'geo_test_harness','agent_type':'deep_engineer','fork_turns':'none','message':message},ensure_ascii=False,indent=2)+'\n')
