import { useState } from 'react';
import { TableShell } from '@/design-system/data-table/table-shell';
import { Button } from '@/design-system/primitives/button';
import type { components } from '@/shared/api/generated/schema';
import { formatTime, modeLabels } from './opportunities.model';

type Evidence = components['schemas']['GeoOpportunitySourceEvidence'];
type Results = components['schemas']['GeoReviewedResults'];
const roleLabels = { TRIGGER: '触发来源', SUPPORTING: '支持来源', BASELINE: '基线来源', RETEST: '复测来源' } satisfies Record<Evidence['source_role'], string>;
function safeCitationUrl(value: string) {
  const url = new URL(value);
  if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password) throw new Error('服务端返回不安全的引用链接');
  return value;
}
export function OpportunityEvidence({ evidence, onRefresh }: { evidence: Evidence; onRefresh: () => void }) {
  const { run, answer, analysis, review } = evidence;
  const frozen = run.input_snapshot;
  return <article aria-label={`历史来源 ${run.id}`} className="min-w-0 space-y-4 border-t border-border-subtle pt-4">
    <header className="space-y-1"><h3 className="type-section-title">{roleLabels[evidence.source_role]} · 尝试 {run.attempt_no}</h3><p className="break-all text-xs text-text-muted">运行 ID：{evidence.run_id} · 来源 ID：{evidence.id} · 关联时间：{formatTime(evidence.created_at)}</p></header>
    <section className="min-w-0 space-y-2" aria-label="冻结运行输入"><h4 className="font-medium">冻结运行输入（只读）</h4><p className="whitespace-pre-wrap break-words">{frozen.prompt.prompt_text}</p><p className="text-sm">{frozen.prompt.canonical_question} · {frozen.prompt.mention_mode} · {frozen.prompt.language_code} / {frozen.prompt.region_code}</p><p className="text-sm">{frozen.profile.surface.name} · {frozen.profile.name} · {modeLabels[frozen.profile.collection_mode]} · 规则修订 {frozen.rule_set_revision}</p><ul className="space-y-1 text-sm">{frozen.subjects.map((subject) => <li key={subject.id} className="break-words [overflow-wrap:anywhere]">{subject.display_name} · 修订 {subject.revision} · {subject.id}</li>)}</ul><details><summary className="cursor-pointer text-sm">完整冻结维度与配置</summary><pre className="mt-2 whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{JSON.stringify(frozen, null, 2)}</pre></details></section>
    <section className="min-w-0 space-y-2" aria-label="历史原始回答"><h4 className="font-medium">历史原始回答（只读）</h4>{answer ? <><p className="text-xs">采集时间：{formatTime(answer.collected_at)} · 格式：{answer.answer_format}</p><p className="break-all text-xs text-text-muted">回答 SHA-256：{answer.answer_sha256}</p><pre className="max-h-[32rem] overflow-y-auto whitespace-pre-wrap break-words text-sm [overflow-wrap:anywhere]">{answer.answer_text}</pre><details><summary className="cursor-pointer text-sm">回答来源与安全载荷摘要</summary><p className="mt-2 text-sm">产品：{answer.source_product ?? '未记录'} · 模型：{answer.source_model ?? '未记录'} · 版本：{answer.source_version ?? '未记录'} · 联网信号：{answer.web_search_observed === null ? '未知' : answer.web_search_observed ? '观察到' : '未观察到'}</p><pre className="mt-2 whitespace-pre-wrap break-words text-xs">{JSON.stringify(answer.raw_payload_summary, null, 2)}</pre></details></> : <p className="text-sm text-text-secondary">此来源没有原始回答。</p>}</section>
    <section className="min-w-0 space-y-2" aria-label="历史原始引用"><h4 className="font-medium">历史原始引用</h4>{evidence.citations.length ? <TableShell regionLabel="机会历史原始引用列表"><thead><tr><th scope="col">位置</th><th scope="col">原始引用</th><th scope="col">采集来源</th></tr></thead><tbody>{evidence.citations.map((citation) => <tr key={citation.id}><td>{citation.position} · {citation.occurrences.join(', ')}</td><td className="max-w-sm break-words [overflow-wrap:anywhere]"><p>{citation.hostname}</p><a className="text-interaction-primary underline" href={safeCitationUrl(citation.normalized_url)} rel="noopener noreferrer" target="_blank">{citation.title ?? citation.original_url}</a></td><td>{citation.extraction_source}</td></tr>)}</tbody></TableShell> : <p className="text-sm">没有原始引用。</p>}</section>
    <section className="min-w-0 space-y-2" aria-label="机会证据文件"><h4 className="font-medium">截图与文件</h4><p className="text-xs text-text-secondary">仅按授权使用内部证据；访问链接限时有效，刷新会重新申请受控链接。</p>{evidence.evidence_files.map((file) => <EvidenceFile file={file} key={`${file.id}:${file.download.url}`} onRefresh={onRefresh} />)}{!evidence.evidence_files.length && <p className="text-sm">没有证据文件。</p>}</section>
    <section className="min-w-0 space-y-3" aria-label="来源绑定历史分析"><h4 className="font-medium">来源绑定的历史机器分析（只读）</h4><p className="break-all text-xs">分析 ID：{evidence.analysis_revision_id ?? '无分析引用'}</p>{analysis ? <><p className="text-sm">分析 Revision {analysis.analysis.revision} · {analysis.analysis.status} · {analysis.analysis.analyzer_type} / {analysis.analysis.analyzer_version}</p><p className="break-all text-xs">输入 SHA-256：{analysis.analysis.input_sha256} · 完成：{formatTime(analysis.analysis.finished_at)}</p><ResultsReadout label="历史机器" results={analysis} evidence={evidence} /><details><summary className="cursor-pointer text-sm">历史分析事实版本绑定与配置</summary><pre className="mt-2 whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{JSON.stringify(analysis.analysis.input_snapshot, null, 2)}</pre></details></> : <p className="text-sm">此来源没有绑定机器分析。</p>}</section>
    <section className="min-w-0 space-y-2" aria-label="来源绑定历史人工复核"><h4 className="font-medium">来源绑定的历史人工复核（只读）</h4><p className="break-all text-xs">复核 ID：{evidence.review_id ?? '无复核引用'}</p>{review ? <><p className="text-sm">{review.decision === 'CONFIRMED' ? '确认机器结论' : '人工修正'} · 复核人 {review.reviewer_id} · {formatTime(review.created_at)}</p><p className="whitespace-pre-wrap break-words text-sm">{review.comment || '未填写复核说明'}</p>{review.correction_payload && <details><summary className="cursor-pointer text-sm">该次完整人工修正</summary><pre className="mt-2 whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{JSON.stringify(review.correction_payload, null, 2)}</pre></details>}</> : <p className="text-sm">此来源没有绑定人工复核。</p>}</section>
    <section className="min-w-0 space-y-3" aria-label="历史有效结果"><h4 className="font-medium">历史有效结果（服务端投影）</h4><p className="text-xs text-text-secondary">严格使用此来源保存的分析与复核身份，不读取运行当前指针。</p>{evidence.effective_results ? <ResultsReadout label="历史有效" results={evidence.effective_results} evidence={evidence} /> : <p className="text-sm">此来源没有历史有效结果。</p>}</section>
  </article>;
}
function ResultsReadout({ results, evidence, label }: { results: Results; evidence: Evidence; label: string }) {
  const subjects = evidence.analysis?.analysis.input_snapshot.subjects ?? evidence.run.input_snapshot.subjects;
  const subjectName = (id: string | null) => id === null ? '未关联对象' : subjects.find((item) => item.id === id)?.display_name ?? id;
  return <div className="min-w-0 space-y-3">
    <details><summary className="cursor-pointer text-sm">提及与推荐</summary><div className="mt-2 space-y-2 text-sm">{results.mentions.map((item) => <p key={item.subject_id}>{subjectName(item.subject_id)}：{item.mention_count} 次 · 首次位置 {item.first_character_offset ?? '未记录'} · {item.matched_aliases.join('、')}</p>)}{!results.mentions.length && <p>无提及结果。</p>}{results.recommendations.map((item) => <p className="break-words" key={item.subject_id}>{subjectName(item.subject_id)}：{item.recommendation} · 排名 {item.rank ?? '未记录'} · {item.rationale_excerpt ?? '无理由摘录'}</p>)}{!results.recommendations.length && <p>无推荐结果。</p>}</div></details>
    {results.claims.length ? <TableShell regionLabel={`${label}声明与事实依据`}><thead><tr><th scope="col">对象 / 声明</th><th scope="col">事实版本 / 依据</th><th scope="col">判定 / 解释</th></tr></thead><tbody>{results.claims.map((claim) => <tr key={claim.id}><td className="max-w-sm whitespace-pre-wrap break-words [overflow-wrap:anywhere]">{subjectName(claim.subject_id)}<p>{claim.claim_kind} · {claim.claim_text}</p></td><td className="max-w-sm whitespace-pre-wrap break-words [overflow-wrap:anywhere]"><p>{claim.fact_version_id ?? '没有事实版本'}</p><p>{claim.fact_excerpt ?? '没有事实摘录'}</p></td><td className="max-w-sm whitespace-pre-wrap break-words [overflow-wrap:anywhere]"><p>{claim.verdict} · {claim.severity}</p><p>{claim.explanation}</p></td></tr>)}</tbody></TableShell> : <p className="text-sm">无声明结果。</p>}
    <details><summary className="cursor-pointer text-sm">引用分类 · {results.citation_classification_complete ? '完整' : '不完整'}</summary><ul className="mt-2 space-y-2 text-sm">{results.citations.map((citation) => <li className="break-words [overflow-wrap:anywhere]" key={citation.citation_id}>{evidence.citations.find((item) => item.id === citation.citation_id)?.original_url ?? citation.citation_id} · {citation.source_category} · {subjectName(citation.subject_id)}</li>)}</ul>{!results.citations.length && <p className="text-sm">无引用分类结果。</p>}</details>
  </div>;
}
function EvidenceFile({ file, onRefresh }: { file: components['schemas']['GeoRunEvidenceFile']; onRefresh: () => void }) {
  const [failed, setFailed] = useState(false);
  return <div className="min-w-0 space-y-2 rounded-lg border border-border-subtle p-3"><p className="break-words text-sm">{file.kind === 'SCREENSHOT' ? '截图证据' : '原始载荷'} · {file.access_level} · {file.size} 字节 · 到期 {formatTime(file.download.expires_at)}</p><p className="break-all text-xs text-text-muted">SHA-256：{file.sha256}</p>{file.kind === 'SCREENSHOT' && !failed && <img alt="机会来源截图证据" className="max-h-[28rem] max-w-full rounded-md object-contain" src={file.download.url} referrerPolicy="no-referrer" onError={() => setFailed(true)} />}{failed && <p role="alert" className="text-sm text-danger">截图加载失败，链接可能已过期。</p>}<div className="flex flex-wrap gap-2"><a className="text-sm text-interaction-primary underline" href={file.download.url} target="_blank" rel="noopener noreferrer">打开受控证据文件</a><Button type="button" variant="outline" size="sm" onClick={onRefresh}>刷新证据访问链接</Button></div></div>;
}
