import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { TablePagination } from '@/design-system/data-table/table-pagination';
import { TableShell } from '@/design-system/data-table/table-shell';
import { Badge } from '@/design-system/primitives/badge';
import { Button } from '@/design-system/primitives/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/design-system/primitives/sheet';
import type { components } from '@/shared/api/generated/schema';
import { opportunityComparisonOptions, opportunityDetailOptions, OpportunityRequestError } from './opportunities.api';
import { formatTime, formatValue, opportunitySearchSchema, priorityLabels, ruleLabels, stageLabels, statusLabels, type OpportunitySearch } from './opportunities.model';
import { OpportunityCommands } from './opportunity-commands';
import { OpportunityComparison } from './opportunity-comparison';
import { OpportunityDecisions } from './opportunity-decisions';
import { canRetryOpportunityRead, canShowOpportunitySnapshot, OpportunityReadFailure } from './opportunity-controls';
import { OpportunityEvidence } from './opportunity-evidence';

export function OpportunityDrawer({ search, csrfToken, onChange, finalFocus, intent }: { search: OpportunitySearch; csrfToken: string | null; onChange: (search: OpportunitySearch) => void; finalFocus: () => HTMLElement | null; intent?: components['schemas']['GeoOpportunityAction'] }) {
  const query = useQuery(opportunityDetailOptions(search));
  const comparisonQuery = useQuery(opportunityComparisonOptions(search));
  const [privacyFailure, setPrivacyFailure] = useState<{ id: string; error: OpportunityRequestError }>();
  const privateError = privacyFailure && privacyFailure.id === search.opportunity_id ? privacyFailure.error : comparisonQuery.error instanceof OpportunityRequestError && [401, 403, 404].includes(comparisonQuery.error.status ?? 0) ? comparisonQuery.error : undefined;
  const detail = !privateError && canShowOpportunitySnapshot(query.error) ? query.data : undefined;
  const comparisonRead = !privateError && canShowOpportunitySnapshot(query.error) && canShowOpportunitySnapshot(comparisonQuery.error) ? comparisonQuery.data : undefined;
  const change = (patch: Partial<OpportunitySearch>) => onChange(opportunitySearchSchema.parse({ ...search, ...patch }));
  async function reload() { const result = await query.refetch({ throwOnError: true }); if (!result.data) throw new Error('机会详情缺少读取结果'); return result.data.opportunity; }
  async function reloadDecision(withComparison: boolean) {
    if (!withComparison) return { opportunity: await reload() };
    const result = await comparisonQuery.refetch({ throwOnError: true });
    if (!result.data) throw new Error('比较快照缺少读取结果');
    return { opportunity: result.data.opportunity, comparisonRead: result.data };
  }
  return <Sheet open={Boolean(search.opportunity_id)} onOpenChange={(open) => { if (!open) { setPrivacyFailure(undefined); change({ opportunity_id: undefined, source_page: undefined, source_page_size: undefined, retest_batch_id: undefined }); } }}><SheetContent className="overflow-y-auto data-[side=right]:w-full data-[side=right]:sm:max-w-4xl" finalFocus={finalFocus}><SheetHeader className="pr-12"><SheetTitle>机会详情与历史证据</SheetTitle><SheetDescription>首次触发、关联评估和来源证据分别保存；关闭机会后仍可读取。</SheetDescription></SheetHeader>
    <div className="min-w-0 space-y-5 px-4 pb-6">
      <p className="break-all text-xs text-text-muted">机会 ID：{search.opportunity_id}</p>{canRetryOpportunityRead(query.error) && <Button type="button" variant="outline" disabled={query.isFetching} onClick={() => void query.refetch()}>刷新详情</Button>}
      {query.isFetching && <p role="status">{query.data ? '正在刷新机会证据…' : '正在读取机会证据…'}</p>}{query.error && <OpportunityReadFailure evidence error={query.error} retained={Boolean(query.data)} onRetry={() => void query.refetch()} />}
      {privateError && !query.error && <OpportunityReadFailure error={privateError} onRetry={() => {}} />}
      {search.opportunity_id && <OpportunityCommands opportunityId={search.opportunity_id} opportunity={detail?.opportunity} key={search.opportunity_id} csrfToken={csrfToken} blocked={Boolean(query.error) || query.isFetching || !detail} intent={intent} onReload={reload} onDenied={(error) => setPrivacyFailure({ id: search.opportunity_id!, error })} />}
      {search.opportunity_id && !privateError && (!query.error || detail) && <OpportunityComparison key={`comparison-${search.opportunity_id}`} data={comparisonRead} selectedBatchId={search.retest_batch_id} fetching={comparisonQuery.isFetching} error={comparisonQuery.error} onSelect={(id) => change({ retest_batch_id: id })} onReload={() => void comparisonQuery.refetch()} />}
      {search.opportunity_id && <OpportunityDecisions key={`decisions-${search.opportunity_id}`} opportunityId={search.opportunity_id} opportunity={detail?.opportunity} comparisonRead={comparisonRead} comparisonBlocked={Boolean(comparisonQuery.error) || comparisonQuery.isFetching || !comparisonRead} blocked={Boolean(query.error) || query.isFetching || !detail || Boolean(privateError)} csrfToken={csrfToken} intent={intent} onReload={reloadDecision} onDenied={(error) => setPrivacyFailure({ id: search.opportunity_id!, error })} />}
      {detail && <>
        <section aria-label="机会概要" className="min-w-0 space-y-3"><h2 className="type-section-title break-words">{detail.opportunity.title}</h2><p className="whitespace-pre-wrap break-words text-sm">{detail.opportunity.description}</p><div className="flex flex-wrap items-center gap-2"><Badge>{priorityLabels[detail.opportunity.priority]}</Badge><Badge>{statusLabels[detail.opportunity.status]}</Badge><span className="text-sm">服务端阶段：{stageLabels[detail.opportunity.workflow_stage]} · revision {detail.opportunity.revision}</span></div><dl className="grid min-w-0 gap-3 text-sm sm:grid-cols-2">{Object.entries({ '规则': ruleLabels[detail.opportunity.rule_code], '当前监测对象': detail.opportunity.subject_name ?? '未限定', '当前问题主题': detail.opportunity.query_topic_name ?? '未限定', '当前问题变体': detail.opportunity.prompt_variant_name ?? '未限定', '当前采集配置': detail.opportunity.collection_profile_name ?? '未限定', '当前观测面': detail.opportunity.engine_surface_name ?? '未限定', '当前产品 ID': detail.opportunity.product_id ?? '未关联产品', '创建时间': formatTime(detail.opportunity.created_at), '最近评估时间': formatTime(detail.opportunity.last_seen_at) }).map(([label, value]) => <div className="min-w-0" key={label}><dt className="text-text-muted">{label}</dt><dd className="break-words [overflow-wrap:anywhere]">{value}</dd></div>)}</dl><p className="text-xs text-text-secondary">名称和产品关联为当前元数据；冻结输入与事实版本见历史来源。</p></section>
        <section aria-label="处理记录" className="min-w-0 space-y-2 border-t border-border-subtle pt-4"><h3 className="type-section-title">处理记录</h3><p className="break-words text-sm">确认：{formatTime(detail.opportunity.acknowledged_at)} · 操作人 {detail.opportunity.acknowledged_by ?? '未记录'}</p><p className="break-words text-sm">关闭：{formatTime(detail.opportunity.resolved_at)} · 操作人 {detail.opportunity.resolved_by ?? '未记录'}</p>{detail.opportunity.resolution_code !== null && <p className="break-words text-sm">关闭原因代码：{detail.opportunity.resolution_code}</p>}{detail.opportunity.resolution_comment !== null && <p className="whitespace-pre-wrap break-words text-sm">关闭原因说明：{detail.opportunity.resolution_comment}</p>}{detail.actions.length ? <TableShell regionLabel="机会已有行动记录"><thead><tr><th scope="col">行动类型 / 目标</th><th scope="col">状态快照</th><th scope="col">登记时间 / 操作人</th></tr></thead><tbody>{detail.actions.map((action) => <tr key={action.id}><td className="max-w-sm break-words [overflow-wrap:anywhere]">{action.action_type} · {action.target_type}<p>{action.target_id}</p>{action.navigation_path && action.target_available === true && <a className="text-interaction-primary underline underline-offset-4" href={action.navigation_path}>打开行动目标</a>}{action.target_available === false && <p className="text-text-secondary">目标已删除，来源快照仍保留。</p>}{action.source_snapshot && <details><summary className="cursor-pointer text-sm">行动来源快照</summary><pre className="mt-2 whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{JSON.stringify(action.source_snapshot, null, 2)}</pre></details>}</td><td>{action.status_snapshot}</td><td className="max-w-sm break-words [overflow-wrap:anywhere]">{formatTime(action.created_at)}<p>{action.created_by}</p></td></tr>)}</tbody></TableShell> : <p className="text-sm text-text-secondary">没有已登记的行动记录。</p>}</section>
        <Snapshot title="首次触发快照（不可变）" snapshot={detail.trigger_snapshot} />
        <section aria-label="最新关联评估" className="min-w-0 space-y-3 border-t border-border-subtle pt-4"><h3 className="type-section-title">最新关联评估</h3>{detail.latest_evaluation ? <><p className="break-all text-xs">评估 ID：{detail.latest_evaluation.id} · {detail.latest_evaluation.disposition} · 规则修订 {detail.latest_evaluation.rule_set_revision}</p><p className="text-sm">评估截止：{formatTime(detail.latest_evaluation.evaluated_as_of)} · 记录时间：{formatTime(detail.latest_evaluation.created_at)}</p><Snapshot title="最新评估结果（只读）" snapshot={detail.latest_evaluation.result_snapshot} /></> : <p className="text-sm">没有最新关联评估记录。</p>}</section>
        <section aria-label="机会历史来源" className="min-w-0 space-y-3 border-t border-border-subtle pt-4"><h3 className="type-section-title">历史来源证据</h3><p className="text-sm">共 {detail.sources.total} 条来源；当前页来自机会来源表，与首次触发快照分开读取。</p>{detail.sources.items.map((evidence) => <OpportunityEvidence evidence={evidence} key={evidence.id} onRefresh={() => void query.refetch()} />)}{!detail.sources.items.length && <p className="text-sm">当前来源页为空。</p>}<TablePagination pageIndex={(search.source_page ?? 1) - 1} pageSize={search.source_page_size ?? 20} pageCount={Math.ceil(detail.sources.total / (search.source_page_size ?? 20))} totalItems={detail.sources.total} onPageIndexChange={(index) => change({ source_page: index + 1 })} onPageSizeChange={(size) => change({ source_page_size: size === 20 ? undefined : size as 10 | 50, source_page: undefined })} />{!detail.sources.items.length && (search.source_page ?? 1) > 1 && <Button type="button" variant="outline" onClick={() => change({ source_page: undefined })}>返回来源第一页</Button>}</section>
        <p className="text-xs text-text-muted">详情快照截止：{formatTime(detail.as_of)}</p>
      </>}
    </div>
  </SheetContent></Sheet>;
}
function Snapshot({ title, snapshot }: { title: string; snapshot: components['schemas']['GeoOpportunityTriggerSnapshot'] }) {
  return <section aria-label={title} className="min-w-0 space-y-2 border-t border-border-subtle pt-4"><h3 className="type-section-title">{title}</h3><p className="text-sm">{ruleLabels[snapshot.rule_code]} · 规则修订 {snapshot.rule_snapshot.rule_set_revision} · {snapshot.triggered ? '已触发' : '未触发'}</p><p className="text-sm">值 {formatValue(snapshot.value)} · 阈值 {formatValue(snapshot.threshold)} · 分子 {snapshot.numerator} / 分母 {snapshot.denominator}</p><p className="text-xs text-text-secondary">来源时间：{formatTime(snapshot.source_date_from)} 至 {formatTime(snapshot.source_date_to)}（不含）</p>{snapshot.unavailable_reasons.length > 0 && <p className="text-sm">不可用原因：{snapshot.unavailable_reasons.join('、')}</p>}<details><summary className="cursor-pointer text-sm">完整规则、作用域与触发依据</summary><pre className="mt-2 whitespace-pre-wrap break-words text-xs [overflow-wrap:anywhere]">{JSON.stringify(snapshot, null, 2)}</pre></details></section>;
}
