/** React Query 键的唯一注册表；工厂返回值与既有数组语义完全一致。 */
import type {
  AuditLogListQuery,
  AIChannelListQuery,
  ContentTaskListQuery,
  GeoInsightQuery,
  GeoMetricsQuery,
  GeoObservationListQuery,
  PlatformAccountListQuery,
  PlatformProfileListQuery,
  UserListQuery,
} from './types';

export const queryKeys = {
  auth: {
    all: ['auth'] as const,
    me: ['auth', 'me'] as const,
    csrf: ['auth', 'csrf'] as const,
  },
  aiChannels: {
    all: ['ai-channels'] as const,
    list: (query: AIChannelListQuery) => ['ai-channels', query] as const,
    detail: (id: string) => ['ai-channel', id] as const,
    models: (id: string) => ['ai-models', id] as const,
    usage: (id: string, period: string) => ['ai-channel-usage', id, period] as const,
    auditLogs: (id: string, page: number, pageSize: number) =>
      ['ai-channel-audit-logs', id, page, pageSize] as const,
  },
  platformTypes: {
    all: ['platform-types'] as const,
  },
  queryTopics: ['query-topics'] as const,
  platformProfiles: {
    all: ['platform-profiles'] as const,
    list: (query: PlatformProfileListQuery) => ['platform-profiles', query] as const,
    detail: (id: string) => ['platform-profile', id] as const,
  },
  platformPrompts: {
    all: ['platform-prompts'] as const,
    detail: (id: string) => ['platform-prompt', id] as const,
  },
  contentHumanizationPrompt: ['content-humanization-prompt'] as const,
  platformAccounts: {
    all: ['platform-accounts'] as const,
    list: (query: PlatformAccountListQuery) => ['platform-accounts', query] as const,
  },
  auditLogs: ['audit-logs'] as const,
  auditLogList: (targetType: string, targetId: string, page: number, pageSize: number) =>
    ['audit-logs', { targetType, targetId, page, pageSize }] as const,
  auditLogListByQuery: (query: AuditLogListQuery) => ['audit-logs', 'list', query] as const,
  auditLogDetail: (id: string) => ['audit-logs', 'detail', id] as const,
  auditLogFilterOptions: ['audit-logs', 'filter-options'] as const,
  contentTasks: {
    all: ['content-tasks'] as const,
    list: (query: ContentTaskListQuery) => ['content-tasks', query] as const,
    optionsAll: ['generation-options'] as const,
    detail: (id: string) => ['content-task', id] as const,
    versions: (id: string) => ['content-versions', id] as const,
    jobs: (id: string) => ['generation-jobs', id] as const,
    options: (id: string) => ['generation-options', id] as const,
  },
  contentVersions: {
    detail: (id: string) => ['content-version', id] as const,
    review: (id: string) => ['content-review-context', id] as const,
  },
  generationJob: (id: string | undefined) => ['generation-job', id] as const,
  products: {
    all: ['products'] as const,
    list: (search: string) => ['products', { search }] as const,
    detail: (id: string) => ['product', id] as const,
    draft: (id: string) => ['facts-draft', id] as const,
    factVersion: (id: string | undefined) => ['fact-version', id] as const,
    factVersions: (id: string | undefined) => ['fact-versions', id] as const,
    factReview: (id: string | undefined) => ['fact-review-context', id] as const,
  },
  publications: {
    all: ['publications'] as const,
    ready: ['publications', 'ready'] as const,
    summary: ['publications', 'summary'] as const,
    package: (id: string) => ['publication-package', id] as const,
    works: (page: number, pageSize: number, status?: string, platformAccountId?: string, contentTaskId?: string) => ['publications', 'works', { page, pageSize, status, platformAccountId, contentTaskId }] as const,
    work: (id: string) => ['publications', 'work', id] as const,
    articles: (page: number, pageSize: number) => ['publications', 'articles', { page, pageSize }] as const,
    article: (id: string) => ['publications', 'article', id] as const,
    articleDeletionPreview: (id: string) => ['publications', 'article-deletion-preview', id] as const,
    issues: (page: number, pageSize: number, status?: string) => ['publications', 'issues', { page, pageSize, status }] as const,
    issue: (id: string) => ['publications', 'issue', id] as const,
    repair: (id: string) => ['publications', 'repair', id] as const,
  },
  dashboard: ['dashboard'] as const,
  geo: {
    all: ['geo'] as const,
    metrics: ['geo', 'metrics'] as const,
    metric: (query: GeoMetricsQuery) => ['geo', 'metrics', query] as const,
    observations: ['geo', 'observations'] as const,
    observationList: (query: GeoObservationListQuery) => ['geo', 'observations', query] as const,
    observation: (id: string) => ['geo', 'observation', id] as const,
    publications: (productId: string | undefined) => ['geo', 'publications', productId] as const,
    insights: ['geo', 'insights'] as const,
    insight: (query: GeoInsightQuery) => ['geo', 'insights', query] as const,
  },
  files: {
    detail: (id: string) => ['file', id] as const,
    download: (id: string) => ['file-download', id] as const,
  },
  users: {
    all: ['users'] as const,
    list: (query: UserListQuery) => ['users', 'list', query] as const,
  },
};
