/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadyHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProducts"];
        put?: never;
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/api/v1/products/{product_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["getProductFactsDraft"];
        put: operations["replaceProductFactsDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/fact-versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["listFactVersions"];
        put?: never;
        post: operations["createFactVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fact-versions/{fact_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_version_id: components["parameters"]["FactVersionId"];
            };
            cookie?: never;
        };
        get: operations["getFactVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fact-versions/{fact_version_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitFactVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fact-versions/{fact_version_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveFactVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fact-versions/{fact_version_id}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestFactVersionChanges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fact-versions/{fact_version_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retireFactVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQueryTopics"];
        put?: never;
        post: operations["createQueryTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query-topics/{query_topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateQueryTopic"];
        trace?: never;
    };
    "/api/v1/platform-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlatformProfiles"];
        put?: never;
        post: operations["createPlatformProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform-profiles/{platform_profile_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlatformProfileVersions"];
        put?: never;
        post: operations["createPlatformProfileVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform-profile-versions/{platform_profile_version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activatePlatformProfileVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform-profile-versions/{platform_profile_version_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retirePlatformProfileVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listContentTasks"];
        put?: never;
        post: operations["createContentTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-tasks/{content_task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_task_id: components["parameters"]["ContentTaskId"];
            };
            cookie?: never;
        };
        get: operations["getContentTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-tasks/{content_task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeContentTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-tasks/{content_task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelContentTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-tasks/{content_task_id}/generation-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGenerationJobs"];
        put?: never;
        post: operations["createGenerationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-tasks/{content_task_id}/content-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listContentTaskVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation-jobs/{generation_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGenerationJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation-jobs/{generation_job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryGenerationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-versions/{content_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContentVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-versions/{content_version_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createContentRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-versions/{content_version_id}/submit-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitContentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-versions/{content_version_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveContentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-versions/{content_version_id}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestContentVersionChanges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-versions/{content_version_id}/compare/{other_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["compareContentVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-versions/{content_version_id}/publication-package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicationPackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publication-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicationCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlatformAccounts"];
        put?: never;
        post: operations["createPlatformAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publication-records/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createManualPublication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publication-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicationRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publication-records/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicationRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publication-records/{publication_id}/{command}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commandPublicationRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo-observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGeoObservations"];
        put?: never;
        post: operations["createGeoObservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGeoMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFileUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeFileUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFileRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abortFileUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFileDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            checks?: {
                [key: string]: string;
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            code: string;
            message: string;
            /** @default {} */
            details: {
                [key: string]: unknown;
            };
            request_id: string;
        };
        PageInfo: {
            page: number;
            page_size: number;
            total: number;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        AuthSession: {
            user: components["schemas"]["User"];
            csrf_token: string;
        };
        CsrfToken: {
            csrf_token: string;
        };
        /** @enum {string} */
        Role: "SYSTEM_ADMIN" | "PRODUCT_EDITOR" | "PRODUCT_REVIEWER" | "CONTENT_EDITOR" | "CONTENT_REVIEWER" | "ANALYST";
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            roles: components["schemas"]["Role"][];
            is_active: boolean;
            revision: number;
            /** Format: date-time */
            created_at: string;
        };
        UserCreate: {
            username: string;
            display_name: string;
            password: string;
            roles: components["schemas"]["Role"][];
        };
        UserUpdate: {
            expected_revision: number;
            display_name: string;
            roles: components["schemas"]["Role"][];
            is_active: boolean;
        };
        UserList: {
            items: components["schemas"]["User"][];
            page: number;
            page_size: number;
            total: number;
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actor_id: string;
            action: string;
            target_type: string;
            /** Format: uuid */
            target_id: string;
            change_summary: {
                [key: string]: unknown;
            };
            request_id: string;
            /** Format: date-time */
            created_at: string;
        };
        AuditLogList: {
            items: components["schemas"]["AuditLog"][];
            page: number;
            page_size: number;
            total: number;
        };
        /** @enum {string} */
        ProductStatus: "ACTIVE" | "RETIRED";
        Product: {
            /** Format: uuid */
            id: string;
            part_number: string;
            brand: string;
            category: string;
            status: components["schemas"]["ProductStatus"];
            revision: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProductCreate: {
            part_number: string;
            brand: string;
            category: string;
        };
        ProductUpdate: {
            expected_revision: number;
            part_number: string;
            brand: string;
            category: string;
            status: components["schemas"]["ProductStatus"];
        };
        ProductList: {
            items: components["schemas"]["Product"][];
            page: number;
            page_size: number;
            total: number;
        };
        ReferencePart: {
            client_key: string;
            part_number: string;
            manufacturer: string;
            category: string;
        };
        /** @enum {string} */
        ParameterValueType: "NUMERIC" | "RANGE" | "TEXT";
        PartParameter: {
            client_key: string;
            /** @description product 或 ReferencePart.client_key */
            owner_key: string;
            key: string;
            name: string;
            value_type: components["schemas"]["ParameterValueType"];
            min_value?: number | null;
            typical_value?: number | null;
            max_value?: number | null;
            text_value?: string | null;
            unit: string;
            test_conditions: string;
            is_critical: boolean;
            evidence_keys: string[];
        };
        /** @enum {string} */
        ReplacementLevel: "FUNCTIONALLY_SIMILAR" | "PARAMETER_COMPATIBLE" | "PIN_COMPATIBLE" | "PIN_TO_PIN" | "PROTOTYPE_VALIDATED" | "TEMPERATURE_VALIDATED" | "MASS_PRODUCTION_VALIDATED";
        ReplacementRelation: {
            client_key: string;
            reference_part_key: string;
            replacement_level: components["schemas"]["ReplacementLevel"];
            conditions: string;
            exclusions: string;
            evidence_keys: string[];
        };
        /** @enum {string} */
        EvidenceType: "DATASHEET" | "TEST_REPORT" | "APPLICATION_NOTE" | "CUSTOMER_AUTHORIZATION" | "OTHER";
        /** @enum {string} */
        Confidentiality: "PUBLIC" | "INTERNAL" | "RESTRICTED";
        Evidence: {
            client_key: string;
            type: components["schemas"]["EvidenceType"];
            title: string;
            version: string;
            /** Format: uri */
            source_url?: string | null;
            /** Format: uuid */
            file_id?: string | null;
            confidentiality: components["schemas"]["Confidentiality"];
        };
        /** @enum {string} */
        ClaimType: "APPROVED" | "PROHIBITED" | "REQUIRED_DISCLOSURE";
        FactClaim: {
            client_key: string;
            type: components["schemas"]["ClaimType"];
            text: string;
            evidence_keys: string[];
        };
        ProductFactsBody: {
            reference_parts: components["schemas"]["ReferencePart"][];
            parameters: components["schemas"]["PartParameter"][];
            replacement_relations: components["schemas"]["ReplacementRelation"][];
            evidences: components["schemas"]["Evidence"][];
            claims: components["schemas"]["FactClaim"][];
        };
        ProductFactsDraftUpdate: components["schemas"]["ProductFactsBody"] & {
            expected_revision: number;
        };
        ProductFactsDraft: components["schemas"]["ProductFactsBody"] & {
            /** Format: uuid */
            product_id: string;
            revision: number;
        };
        /** @enum {string} */
        FactVersionStatus: "DRAFT" | "PENDING_REVIEW" | "CHANGES_REQUESTED" | "APPROVED" | "RETIRED";
        CreateVersionRequest: {
            change_summary: string;
        };
        CommandRequest: {
            expected_revision: number;
            comment: string;
        };
        FactVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            version: number;
            status: components["schemas"]["FactVersionStatus"];
            snapshot: components["schemas"]["ProductFactsBody"];
            change_summary: string;
            revision: number;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            approved_by?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            approved_at?: string | null;
        };
        FactVersionList: {
            items: components["schemas"]["FactVersion"][];
        };
        /** @enum {string} */
        IntentType: "BRAND" | "PRODUCT" | "REPLACEMENT" | "COMPARISON" | "APPLICATION" | "TROUBLESHOOTING";
        QueryTopicCreate: {
            canonical_question: string;
            intent_type: components["schemas"]["IntentType"];
            variants: string[];
        };
        QueryTopicUpdate: {
            expected_revision: number;
            canonical_question: string;
            intent_type: components["schemas"]["IntentType"];
            variants: string[];
        };
        QueryTopic: components["schemas"]["QueryTopicCreate"] & {
            /** Format: uuid */
            id: string;
            revision: number;
            /** Format: date-time */
            created_at: string;
        };
        QueryTopicList: {
            items: components["schemas"]["QueryTopic"][];
        };
        PlatformProfileCreate: {
            name: string;
            slug: string;
            allowed_domains: string[];
            rules: components["schemas"]["PlatformRules"];
        };
        PlatformProfileVersionCreate: {
            rules: components["schemas"]["PlatformRules"];
        };
        PlatformRules: {
            target_audience: string;
            title_min: number;
            title_max: number;
            body_min: number;
            body_max: number;
            tone: string;
            allow_external_links: boolean;
            allow_tables: boolean;
            allow_contact: boolean;
            prohibited_phrases: string[];
            sections: components["schemas"]["PlatformSection"][];
        };
        PlatformSection: {
            name: string;
            /** Format: uri */
            url: string;
        };
        PlatformProfileVersion: {
            /** Format: uuid */
            id: string;
            version: number;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "RETIRED";
            rules: components["schemas"]["PlatformRules"];
            revision: number;
            /** Format: date-time */
            created_at: string;
        };
        PlatformProfileVersionList: {
            items: components["schemas"]["PlatformProfileVersion"][];
        };
        PlatformProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            allowed_domains: string[];
            active_version: components["schemas"]["PlatformProfileVersion"];
        };
        PlatformProfileList: {
            items: components["schemas"]["PlatformProfile"][];
        };
        /** @enum {string} */
        ContentTaskStatus: "OPEN" | "COMPLETED" | "CANCELLED";
        ContentTaskCreate: {
            /** Format: uuid */
            query_topic_id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            fact_version_id: string;
            /** Format: uuid */
            platform_profile_version_id: string;
            target_audience: string;
            content_angle: string;
            conversion_goal: string;
            desired_format: string;
            desired_length_min: number;
            desired_length_max: number;
            /** Format: uri */
            canonical_url: string;
        };
        ContentTask: components["schemas"]["ContentTaskCreate"] & {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ContentTaskStatus"];
            revision: number;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        ContentTaskList: {
            items: components["schemas"]["ContentTask"][];
        };
        /** @enum {string} */
        GenerationJobStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
        GenerationJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            content_task_id: string;
            status: components["schemas"]["GenerationJobStatus"];
            attempt_count: number;
            /** Format: uuid */
            content_version_id?: string | null;
            /** Format: uuid */
            retry_of_id?: string | null;
            error_code?: string | null;
            error_summary?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        GenerationJobList: {
            items: components["schemas"]["GenerationJob"][];
        };
        /** @enum {string} */
        ContentVersionStatus: "DRAFT" | "PENDING_REVIEW" | "CHANGES_REQUESTED" | "APPROVED" | "SUPERSEDED";
        QualityIssue: {
            code: string;
            /** @enum {string} */
            severity: "WARNING" | "BLOCKING";
            message: string;
        };
        ContentVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            task_id: string;
            /** Format: uuid */
            fact_version_id: string;
            version: number;
            /** @enum {string} */
            source_type: "AI" | "HUMAN";
            title: string;
            summary: string;
            body_markdown: string;
            tags: string[];
            used_fact_ids?: string[];
            used_evidence_ids?: string[];
            content_hash: string;
            status: components["schemas"]["ContentVersionStatus"];
            revision: number;
            quality_issues: components["schemas"]["QualityIssue"][];
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        ContentRevisionCreate: {
            title: string;
            summary: string;
            body_markdown: string;
            tags: string[];
            change_summary: string;
        };
        ContentVersionList: {
            items: components["schemas"]["ContentVersion"][];
        };
        DiffLine: {
            /** @enum {string} */
            kind: "EQUAL" | "ADD" | "DELETE";
            old_line?: number | null;
            new_line?: number | null;
            text: string;
        };
        ContentDiff: {
            /** Format: uuid */
            left_id: string;
            /** Format: uuid */
            right_id: string;
            lines: components["schemas"]["DiffLine"][];
        };
        PublicationPackage: {
            /** Format: uuid */
            content_version_id: string;
            /** Format: uuid */
            fact_version_id: string;
            title: string;
            body_markdown: string;
            body_html: string;
            body_text: string;
            tags: string[];
            /** Format: uri */
            canonical_url: string;
            content_hash: string;
        };
        PlatformAccountCreate: {
            /** Format: uuid */
            platform_profile_id: string;
            label: string;
            account_identifier: string;
        };
        PlatformAccount: components["schemas"]["PlatformAccountCreate"] & {
            /** Format: uuid */
            id: string;
            is_active: boolean;
        };
        PlatformAccountList: {
            items: components["schemas"]["PlatformAccount"][];
        };
        ManualPublicationCreate: {
            /** Format: uuid */
            content_version_id: string;
            /** Format: uuid */
            platform_account_id: string;
            /** Format: uri */
            section_url: string;
            attachment_file_ids?: string[];
        };
        /** @enum {string} */
        PublicationStatus: "PENDING_MANUAL_PUBLISH" | "PLATFORM_REVIEW" | "PUBLISHED" | "VERIFIED" | "REJECTED" | "REMOVED" | "VERIFICATION_FAILED";
        PublicationCommand: {
            actual_title?: string | null;
            /** Format: uri */
            final_url?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            content_matches?: boolean | null;
            comment: string;
        };
        PublicationRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            content_version_id: string;
            /** Format: uuid */
            platform_account_id: string;
            /** Format: uri */
            section_url: string;
            actual_title?: string | null;
            /** Format: uri */
            final_url?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            status: components["schemas"]["PublicationStatus"];
            content_hash: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            status_events: components["schemas"]["PublicationEvent"][];
            attachments: components["schemas"]["FileRecord"][];
        };
        PublicationRecordList: {
            items: components["schemas"]["PublicationRecord"][];
            page: number;
            page_size: number;
            total: number;
        };
        PublicationEvent: {
            status: components["schemas"]["PublicationStatus"];
            comment: string;
            /** Format: uuid */
            actor_id: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        RecommendationStatus: "NONE" | "CANDIDATE" | "RECOMMENDED";
        /** @enum {string} */
        AccuracyStatus: "ACCURATE" | "PARTIAL" | "INCORRECT" | "UNJUDGEABLE";
        /** @enum {string} */
        CitationSourceType: "OFFICIAL" | "EXTERNAL_COMPANY" | "OTHER";
        GeoCitation: {
            /** Format: uri */
            url: string;
            source_type: components["schemas"]["CitationSourceType"];
            /** Format: uuid */
            publication_record_id?: string | null;
        };
        GeoObservationCreate: {
            /** Format: uuid */
            query_topic_id: string;
            /** Format: uuid */
            product_id: string;
            actual_prompt: string;
            model_name: string;
            model_version?: string | null;
            /** Format: date-time */
            tested_at: string;
            web_search_enabled: boolean;
            answer_summary: string;
            mentioned: boolean;
            recommendation: components["schemas"]["RecommendationStatus"];
            accuracy: components["schemas"]["AccuracyStatus"];
            citations: components["schemas"]["GeoCitation"][];
            publication_record_ids: string[];
            attachment_file_ids?: string[];
            notes: string;
            /** Format: uuid */
            supersedes_id?: string | null;
        };
        GeoObservation: components["schemas"]["GeoObservationCreate"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tested_by: string;
            /** Format: date-time */
            created_at: string;
        };
        GeoObservationList: {
            items: components["schemas"]["GeoObservation"][];
        };
        GeoMetrics: {
            sample_count: number;
            mention_rate: number;
            recommendation_rate: number;
            citation_rate: number;
            accuracy_rate: number | null;
        };
        DashboardSummary: {
            pending_fact_reviews: number;
            pending_content_reviews: number;
            pending_publications: number;
            publication_attention: number;
            recent_accuracy_errors: number;
        };
        /** @enum {string} */
        FileCategory: "EVIDENCE" | "OPERATION_SCREENSHOT" | "PUBLICATION_ASSET";
        UploadIntentCreate: {
            category: components["schemas"]["FileCategory"];
            original_filename: string;
            content_type: string;
            size: number;
            sha256: string;
            access_level: components["schemas"]["Confidentiality"];
        };
        UploadInstruction: {
            /** @enum {string} */
            method: "PUT" | "POST";
            /** Format: uri */
            url: string;
            headers: {
                [key: string]: string;
            };
            fields: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        UploadIntent: {
            file: components["schemas"]["FileRecord"];
            upload: components["schemas"]["UploadInstruction"];
        };
        FileRecord: {
            /** Format: uuid */
            id: string;
            category: components["schemas"]["FileCategory"];
            original_filename: string;
            object_key: string;
            content_type: string;
            size: number;
            sha256: string;
            access_level: components["schemas"]["Confidentiality"];
            /** @enum {string} */
            status: "PENDING" | "VERIFIED" | "FAILED" | "ABORTED";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            verified_at?: string | null;
        };
        SignedUrl: {
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expires_at: string;
        };
    };
    responses: {
        /** @description 业务或校验错误 */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 更新后的事实版本 */
        FactVersionResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["FactVersion"];
            };
        };
        /** @description 更新后的内容版本 */
        ContentVersionResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ContentVersion"];
            };
        };
    };
    parameters: {
        CsrfHeader: string;
        IdempotencyKey: string;
        Page: number;
        PageSize: number;
        ProductId: string;
        FactVersionId: string;
        PlatformProfileId: string;
        PlatformProfileVersionId: string;
        ContentTaskId: string;
        GenerationJobId: string;
        ContentVersionId: string;
        PublicationId: string;
        FileId: string;
    };
    requestBodies: {
        CommandRequest: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadyHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PostgreSQL 和 Redis 就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            503: components["responses"]["ErrorResponse"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功并设置会话 Cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销会话 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前会话 CSRF Token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
            403: components["responses"]["ErrorResponse"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description 已更新用户角色或启用状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                target_type?: string;
                target_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 追加式审计日志 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogList"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 产品列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 产品详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    getProductFactsDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前事实工作区 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductFactsDraft"];
                };
            };
        };
    };
    replaceProductFactsDraft: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductFactsDraftUpdate"];
            };
        };
        responses: {
            /** @description 已保存事实工作区 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductFactsDraft"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    listFactVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事实版本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactVersionList"];
                };
            };
        };
    };
    createFactVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                product_id: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVersionRequest"];
            };
        };
        responses: {
            /** @description 已从工作区创建不可变快照 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactVersion"];
                };
            };
            422: components["responses"]["ErrorResponse"];
        };
    };
    getFactVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_version_id: components["parameters"]["FactVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事实版本详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactVersion"];
                };
            };
        };
    };
    submitFactVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                fact_version_id: components["parameters"]["FactVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            200: components["responses"]["FactVersionResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    approveFactVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                fact_version_id: components["parameters"]["FactVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            200: components["responses"]["FactVersionResponse"];
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    requestFactVersionChanges: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                fact_version_id: components["parameters"]["FactVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            200: components["responses"]["FactVersionResponse"];
        };
    };
    retireFactVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                fact_version_id: components["parameters"]["FactVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            200: components["responses"]["FactVersionResponse"];
        };
    };
    listQueryTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目标问题列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryTopicList"];
                };
            };
        };
    };
    createQueryTopic: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryTopicCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryTopic"];
                };
            };
        };
    };
    updateQueryTopic: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                query_topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryTopicUpdate"];
            };
        };
        responses: {
            /** @description 已更新目标问题 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryTopic"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    listPlatformProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 平台配置列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProfileList"];
                };
            };
        };
    };
    createPlatformProfile: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformProfileCreate"];
            };
        };
        responses: {
            /** @description 已创建平台和首个 ACTIVE 版本 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProfile"];
                };
            };
        };
    };
    listPlatformProfileVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform_profile_id: components["parameters"]["PlatformProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 平台全部规则版本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProfileVersionList"];
                };
            };
        };
    };
    createPlatformProfileVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                platform_profile_id: components["parameters"]["PlatformProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformProfileVersionCreate"];
            };
        };
        responses: {
            /** @description 已创建 DRAFT 配置版本 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProfileVersion"];
                };
            };
        };
    };
    activatePlatformProfileVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                platform_profile_version_id: components["parameters"]["PlatformProfileVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            /** @description 已激活并停用上一 ACTIVE 版本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProfileVersion"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    retirePlatformProfileVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                platform_profile_version_id: components["parameters"]["PlatformProfileVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            /** @description 已停用平台配置版本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProfileVersion"];
                };
            };
        };
    };
    listContentTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 内容任务列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentTaskList"];
                };
            };
        };
    };
    createContentTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentTaskCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentTask"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    getContentTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_task_id: components["parameters"]["ContentTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 内容任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentTask"];
                };
            };
        };
    };
    completeContentTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                content_task_id: components["parameters"]["ContentTaskId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            /** @description 已完成内容任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentTask"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    cancelContentTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                content_task_id: components["parameters"]["ContentTaskId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            /** @description 已取消内容任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentTask"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    listGenerationJobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_task_id: components["parameters"]["ContentTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务的全部生成作业 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobList"];
                };
            };
        };
    };
    createGenerationJob: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                content_task_id: components["parameters"]["ContentTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已创建或返回幂等作业 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJob"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    listContentTaskVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_task_id: components["parameters"]["ContentTaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务的全部内容版本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentVersionList"];
                };
            };
        };
    };
    getGenerationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_job_id: components["parameters"]["GenerationJobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 生成作业 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJob"];
                };
            };
        };
    };
    retryGenerationJob: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                generation_job_id: components["parameters"]["GenerationJobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已创建重试作业 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJob"];
                };
            };
        };
    };
    getContentVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_version_id: components["parameters"]["ContentVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 内容版本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentVersion"];
                };
            };
        };
    };
    createContentRevision: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                content_version_id: components["parameters"]["ContentVersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentRevisionCreate"];
            };
        };
        responses: {
            /** @description 已创建新版本 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentVersion"];
                };
            };
        };
    };
    submitContentVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                content_version_id: components["parameters"]["ContentVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            200: components["responses"]["ContentVersionResponse"];
        };
    };
    approveContentVersion: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                content_version_id: components["parameters"]["ContentVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            200: components["responses"]["ContentVersionResponse"];
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    requestContentVersionChanges: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                content_version_id: components["parameters"]["ContentVersionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CommandRequest"];
        responses: {
            200: components["responses"]["ContentVersionResponse"];
        };
    };
    compareContentVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_version_id: components["parameters"]["ContentVersionId"];
                other_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Markdown 行级差异 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDiff"];
                };
            };
        };
    };
    getPublicationPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_version_id: components["parameters"]["ContentVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 由批准 Markdown 派生的人工发布包 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationPackage"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    listPublicationCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可人工发布的批准内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentVersionList"];
                };
            };
        };
    };
    listPlatformAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 平台账号标识 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountList"];
                };
            };
        };
    };
    createPlatformAccount: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformAccountCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccount"];
                };
            };
        };
    };
    createManualPublication: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPublicationCreate"];
            };
        };
        responses: {
            /** @description 已创建人工发布记录 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRecord"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    listPublicationRecords: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                status?: components["schemas"]["PublicationStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布记录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRecordList"];
                };
            };
        };
    };
    getPublicationRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: components["parameters"]["PublicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRecord"];
                };
            };
        };
    };
    commandPublicationRecord: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                publication_id: components["parameters"]["PublicationId"];
                command: "mark-platform-review" | "mark-published" | "verify" | "reject" | "remove" | "mark-verification-failed";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationCommand"];
            };
        };
        responses: {
            /** @description 已执行状态命令 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRecord"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    listGeoObservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 观测列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoObservationList"];
                };
            };
        };
    };
    createGeoObservation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeoObservationCreate"];
            };
        };
        responses: {
            /** @description 已追加观测 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoObservation"];
                };
            };
        };
    };
    getGeoMetrics: {
        parameters: {
            query?: {
                product_id?: string;
                query_topic_id?: string;
                model_name?: string;
                date_from?: string;
                date_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 基础 GEO 指标 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoMetrics"];
                };
            };
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 需要行动的工作台摘要 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    createFileUploadIntent: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIntentCreate"];
            };
        };
        responses: {
            /** @description 已创建限时上传意图 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntent"];
                };
            };
        };
    };
    completeFileUpload: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                file_id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HEAD 校验成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRecord"];
                };
            };
            422: components["responses"]["ErrorResponse"];
        };
    };
    getFileRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文件元数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRecord"];
                };
            };
        };
    };
    abortFileUpload: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path: {
                file_id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已中止未完成上传 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRecord"];
                };
            };
            409: components["responses"]["ErrorResponse"];
        };
    };
    getFileDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 短期下载 URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrl"];
                };
            };
        };
    };
}
