/** 为业务组件导出 OpenAPI Schema 的简短别名，不重新定义传输对象。 */
import type { components, paths } from './schema';

export type Schema<Name extends keyof components['schemas']> = components['schemas'][Name];
export type User = Schema<'User'>;
export type AccountType = Schema<'AccountType'>;
export type Product = Schema<'Product'>;
export type ProductFactsDraft = Schema<'ProductFactsDraft'>;
export type FactVersion = Schema<'FactVersion'>;
export type QueryTopic = Schema<'QueryTopic'>;
export type PlatformProfile = Schema<'PlatformProfile'>;
export type PlatformPrompt = Schema<'PlatformPromptDetail'>;
export type ContentTask = Schema<'ContentTask'>;
export type ContentTaskListItem = Schema<'ContentTaskListItem'>;
export type GenerationJob = Schema<'GenerationJob'>;
export type AIChannel = Schema<'AIChannel'>;
export type AIChannelSummary = Schema<'AIChannelSummary'>;
export type AIModel = Schema<'AIModel'>;
export type PlatformType = Schema<'PlatformType'>;
export type ContentVersion = Schema<'ContentVersion'>;
export type PublicationRecord = Schema<'PublicationRecord'>;
export type GeoObservation = Schema<'GeoObservation'>;
export type FileRecord = Schema<'FileRecord'>;
export type GeoObservationListQuery = NonNullable<paths['/api/v1/geo-observations']['get']['parameters']['query']>;
export type GeoMetricsQuery = NonNullable<paths['/api/v1/geo-metrics']['get']['parameters']['query']>;
export type GeoInsightQuery = NonNullable<paths['/api/v1/geo-insights']['get']['parameters']['query']>;
export type AIChannelListQuery = NonNullable<paths['/api/v1/ai-channels']['get']['parameters']['query']>;
export type PlatformProfileListQuery = NonNullable<paths['/api/v1/platform-profiles']['get']['parameters']['query']>;
export type PlatformProfileExportQuery = NonNullable<paths['/api/v1/platform-profiles/export']['get']['parameters']['query']>;
export type ContentTaskListQuery = NonNullable<paths['/api/v1/content-tasks']['get']['parameters']['query']>;
export type PlatformAccountListQuery = NonNullable<paths['/api/v1/platform-accounts']['get']['parameters']['query']>;
export type UserListQuery = NonNullable<paths['/api/v1/users']['get']['parameters']['query']>;
export type UserExportQuery = NonNullable<paths['/api/v1/users/export']['get']['parameters']['query']>;
export type AuditLogListQuery = NonNullable<paths['/api/v1/audit-logs']['get']['parameters']['query']>;
