import type { components } from '@/shared/api/generated/schema';
import { TableShell } from '@/design-system/data-table/table-shell';
import { exclusionLabels, formatTime } from './insights.model';
import type { InsightDetail } from './insights.api';
import { safeCitationUrl } from './insights-components';

type Sample = components['schemas']['GeoOverviewRunSample'];
function SampleIdentity({ item }: { item: Pick<Sample, 'run_id' | 'batch_id' | 'created_at' | 'analysis_revision_id' | 'review_id'> }) {
  return <div className="max-w-xs space-y-1 break-all text-xs"><a className="text-primary underline" href={`/geo/runs?view=runs&run_id=${encodeURIComponent(item.run_id)}`}>运行 {item.run_id}</a><p>批次：{item.batch_id}</p><p>{formatTime(item.created_at)}</p><p>分析 revision：{item.analysis_revision_id ?? '无'}</p><p>复核：{item.review_id ?? '无有效复核'}</p></div>;
}
export function InsightSampleTables({ detail }: { detail: InsightDetail }) {
  if (!detail.page.items.length) return <p className="text-sm" role="status">当前明细页没有样本。可调整组成集合或返回第一页。</p>;
  switch (detail.kind) {
    case 'overview': case 'metric': return <TableShell regionLabel="指标组成样本表"><thead><tr><th scope="col">运行与不可变分析</th><th scope="col">状态</th><th scope="col">分子贡献</th><th scope="col">分母贡献</th><th scope="col">排除原因</th></tr></thead><tbody>{detail.page.items.map((item) => <tr key={item.run_id}><th scope="row"><SampleIdentity item={item}/></th><td>{item.status}</td><td>{item.numerator}</td><td>{item.denominator}</td><td>{item.exclusion_reasons.length ? item.exclusion_reasons.map((reason) => exclusionLabels[reason]).join('；') : '无'}</td></tr>)}</tbody></TableShell>;
    case 'citations': return <><p className="text-sm">匹配运行数：{detail.page.run_count} · 引用条数：{detail.page.total}</p><TableShell regionLabel="引用证据明细表"><thead><tr><th scope="col">运行与不可变分析</th><th scope="col">引用</th><th scope="col">分类与出现位置</th><th scope="col">归属和共享域候选</th></tr></thead><tbody>{detail.page.items.map((item) => { const url = safeCitationUrl(item.normalized_url); return <tr key={`${item.run_id}-${item.citation_id}`}><th scope="row"><SampleIdentity item={item}/></th><td className="max-w-md break-all"><p>{item.title ?? '无标题'}</p>{url ? <a className="text-primary underline" href={url} target="_blank" rel="noopener noreferrer">{item.normalized_url}</a> : <p>非安全网页链接：{item.normalized_url}</p>}<p className="text-xs">引用 ID：{item.citation_id}</p></td><td>{item.source_category}<p>出现位置：{item.occurrences.join('、')}</p><p className="break-all">域名：{item.hostname}</p></td><td className="max-w-xs break-all"><p>归属对象：{item.attributed_subject_id ?? '尚未确定归属'}</p><p>共享域：{item.shared_domain ? '是' : '否'}</p><p>候选对象：{item.candidate_subject_ids.length ? item.candidate_subject_ids.join('、') : '无'}</p>{item.shared_domain && <p className="text-xs text-text-secondary">候选对象不代表确定归属。</p>}</td></tr>; })}</tbody></TableShell></>;
    case 'claims': return <><p className="text-sm">匹配运行数：{detail.page.run_count} · 声明条数：{detail.page.total}</p><TableShell regionLabel="事实风险声明明细表"><thead><tr><th scope="col">运行与不可变分析</th><th scope="col">声明与结论</th><th scope="col">事实版本与证据</th></tr></thead><tbody>{detail.page.items.map((item) => <tr key={item.claim_assessment_id}><th scope="row"><SampleIdentity item={item}/></th><td className="max-w-md whitespace-pre-wrap break-words"><p>{item.claim_text}</p><p>{item.claim_kind} · {item.verdict} · {item.severity}</p><p className="text-xs">{item.explanation}</p></td><td className="max-w-md whitespace-pre-wrap break-words"><p className="break-all">对象：{item.subject_id}</p><p className="break-all">事实版本：{item.fact_version_id ?? '未绑定事实版本'}</p><p>{item.fact_excerpt ?? '无事实片段'}</p><p className="break-all text-xs">声明 ID：{item.claim_assessment_id}</p></td></tr>)}</tbody></TableShell></>;
    case 'quality': return <TableShell regionLabel="数据质量运行明细表"><thead><tr><th scope="col">运行与不可变分析</th><th scope="col">贡献与排除</th><th scope="col">费用与版本</th><th scope="col">复核和共享域</th></tr></thead><tbody>{detail.page.items.map((item) => <tr key={item.run_id}><th scope="row"><SampleIdentity item={item}/></th><td><p>{item.status} · 分子 {item.numerator} / 分母 {item.denominator}</p><p>{item.exclusion_reasons.map((reason) => exclusionLabels[reason]).join('；') || '无排除原因'}</p></td><td className="max-w-xs break-all"><p>费用：{item.cost_amount === null ? '未知' : `${item.cost_amount} ${item.cost_currency}`}</p><p>模型：{item.source_model ?? '未知'}</p><p>产品：{item.source_product ?? '未知'}</p><p>来源版本：{item.source_version ?? '未知'}</p><p>分析器：{item.analyzer_version ?? '未知'}</p><p>规则：{item.rule_set_version ?? '未知'}</p><p>分析配置：{item.analysis_configuration_key ?? '未知'}</p></td><td className="max-w-xs break-all"><p>需要复核：{item.review_required ? '是' : '否'} · 当前有效复核：{item.current_review_valid ? '是' : '否'}</p><p>复核原因：{item.review_required_reasons.join('、') || '无'}</p><p>共享域引用：{item.shared_domain_citation_ids.join('、') || '无'}</p></td></tr>)}</tbody></TableShell>;
  }
}
