"""导入全部 ORM 模块以向共享 metadata 注册映射。"""

import app.models.ai_generation  # noqa: F401
import app.models.configuration  # noqa: F401
import app.models.content  # noqa: F401
import app.models.geo_analysis  # noqa: F401
import app.models.geo_analysis_worker  # noqa: F401
import app.models.geo_answers  # noqa: F401
import app.models.geo_batch_creation  # noqa: F401
import app.models.geo_browser_sessions  # noqa: F401
import app.models.geo_catalog  # noqa: F401
import app.models.geo_collection_admission  # noqa: F401
import app.models.geo_files  # noqa: F401
import app.models.geo_manual_collection  # noqa: F401
import app.models.geo_monitoring_plans  # noqa: F401
import app.models.geo_opportunities  # noqa: F401
import app.models.geo_opportunity_decisions  # noqa: F401
import app.models.geo_prompt_variants  # noqa: F401
import app.models.geo_retests  # noqa: F401
import app.models.geo_rules  # noqa: F401
import app.models.geo_runs  # noqa: F401
import app.models.geo_surfaces  # noqa: F401
import app.models.identity  # noqa: F401
import app.models.product_facts  # noqa: F401
import app.models.publication  # noqa: F401
