import type { components } from '@/shared/api/generated/schema';
const runId = '10000000-0000-4000-8000-000000000001';
const batchId = '10000000-0000-4000-8000-000000000002';
const asOf = '2026-10-02T10:00:00Z';
function summary(): components['schemas']['GeoBatchSummary'] {
  return {
    requested_run_count: 3,
    attempt_count: 4,
    pending_manual_count: 2,
    status_counts: {
      pending: 2,
      running: 0,
      collected: 1,
      analyzing: 0,
      needs_review: 0,
      completed: 0,
      failed: 1,
      cancelled: 0,
      budget_blocked: 0,
    },
    cost: { known_attempt_count: 1, unknown_attempt_count: 3, known_costs: [{ value: '0.12', currency: 'USD' }] },
  };
}
function batch(): components['schemas']['GeoBatchListItem'] {
  return {
    id: batchId,
    plan_id: runId,
    plan_name: '冻结计划',
    plan_revision: 7,
    trigger_type: 'MANUAL',
    revision: 3,
    created_by: runId,
    scheduled_for: null,
    created_at: asOf,
    started_at: null,
    finished_at: null,
    summary: summary(),
    status: 'RUNNING',
    workflow_stage: 'MANUAL_ENTRY_REQUIRED',
    primary_task: 'ENTER_MANUAL_OBSERVATIONS',
    available_actions: [],
  };
}
function run(
  overrides: Partial<components['schemas']['GeoRunListItem']> = {},
): components['schemas']['GeoRunListItem'] {
  return {
    id: runId,
    batch_id: batchId,
    prompt_variant_id: runId,
    collection_profile_id: runId,
    run_cell_key: 'a'.repeat(64),
    repeat_index: 1,
    attempt_no: 1,
    previous_attempt_id: null,
    status: 'PENDING',
    revision: 1,
    external_call_state: 'NOT_STARTED',
    lease_expires_at: null,
    dispatch_attempt_count: 0,
    last_dispatch_attempt_at: null,
    error_stage: null,
    error_code: null,
    error_summary: null,
    provider_request_id: null, provider_status: null, retry_after_seconds: null,
    duration_ms: null,
    cost_amount: null,
    cost_currency: null,
    prompt_tokens: null,
    completion_tokens: null,
    total_tokens: null,
    started_at: null,
    collected_at: null,
    finished_at: null,
    created_at: asOf,
    answer_snapshot_id: null,
    collection_eligible: true,
    collection_blockers: [],
    frozen_binding_matches: true,
    is_latest_attempt: true,
    workflow_stage: 'MANUAL_ENTRY_REQUIRED',
    primary_task: 'ENTER_MANUAL_OBSERVATION',
    available_actions: ['ENTER_MANUAL_OBSERVATION'],
    input_snapshot: {
      schema_version: 1,
      data_classification: 'PUBLIC',
      rule_set_revision: 1,
      subjects: [
        {
          id: runId,
          revision: 1,
          subject_type: 'REFERENCE_PART',
          role: 'PRIMARY',
          product_id: null,
          parent_subject_id: null,
          canonical_name: '参考零件',
          display_name: '参考零件',
          aliases: [],
          domains: [],
        },
      ],
      prompt: {
        id: runId,
        revision: 1,
        query_topic_id: runId,
        query_topic_revision: 1,
        canonical_question: '冻结标准问题',
        prompt_text: '冻结完整问题',
        intent_type: 'PRODUCT',
        mention_mode: 'UNBRANDED',
        priority: 'STANDARD',
        language_code: 'zh-CN',
        region_code: 'CN',
      },
      profile: {
        id: runId,
        revision: 1,
        name: '人工配置',
        adapter_key: 'manual',
        adapter_version: '1',
        collection_mode: 'MANUAL',
        ai_channel_id: null,
        ai_model_id: null,
        login_state: 'ANONYMOUS',
        language_code: 'zh-CN',
        region_code: 'CN',
        web_search_policy: 'UNKNOWN',
        settings: { require_screenshot: true },
        surface: {
          id: runId,
          revision: 1,
          name: '人工观测面',
          surface_kind: 'CONSUMER_UI',
          provider_brand: 'CUSTOM',
          compliance_status: 'APPROVED',
          capabilities: {
            answer_text: true,
            citations: true,
            web_search_signal: true,
            model_version: false,
            usage: false,
            cost: false,
          },
        },
      },
    },
    ...overrides,
  };
}
function detail(): components['schemas']['GeoRunDetail'] {
  const current = run({
    status: 'COLLECTED',
    collected_at: asOf,
    available_actions: [],
    workflow_stage: 'ANALYSIS_PENDING',
    primary_task: 'VIEW_EXECUTION_PROGRESS',
  });
  return {
    run: current,
    batch: batch(),
    answer: {
      id: batchId,
      run_id: runId,
      prompt_text: '冻结完整问题',
      answer_text: '<script>danger()</script>原始回答',
      answer_sha256: 'b'.repeat(64),
      answer_format: 'HTML_TEXT',
      source_product: null,
      source_model: null,
      source_version: null,
      web_search_observed: null,
      raw_payload_summary: { schema_version: 1, payload_format: null, payload_bytes: null, finish_reason: null },
      raw_payload_file_id: null,
      screenshot_file_id: batchId,
      citation_count: 1,
      collected_at: asOf,
      created_at: asOf,
    },
    citations: [
      {
        id: batchId,
        answer_snapshot_id: batchId,
        original_url: 'https://example.test/spec',
        normalized_url: 'https://example.test/spec',
        hostname: 'example.test',
        title: '规格引用',
        position: 1,
        occurrences: [1, 3],
        extraction_source: 'MANUAL',
        created_at: asOf,
      },
    ],
    evidence_files: [
      {
        id: batchId,
        kind: 'SCREENSHOT',
        content_type: 'image/png',
        size: 70,
        sha256: 'c'.repeat(64),
        access_level: 'INTERNAL',
        download: { url: 'https://evidence.test/file?signature=temporary', expires_at: asOf },
      },
    ],
    attempts: [
      {
        id: runId,
        attempt_no: 1,
        previous_attempt_id: null,
        status: 'COLLECTED',
        error_stage: null,
        error_code: null,
        error_summary: null,
        created_at: asOf,
        started_at: null,
        collected_at: asOf,
        finished_at: null,
      },
    ],
    timeline: [
      { run_id: runId, attempt_no: 1, event: 'CREATED', occurred_at: asOf },
      { run_id: runId, attempt_no: 1, event: 'COLLECTED', occurred_at: asOf },
    ],
    analysis: {
      selection: { run_id: runId, current_analysis_revision_id: null, current_review_id: null },
      revisions: [],
      reviews: [],
      effective_results: null,
      review_required: false,
      review_gate_passed: false,
      available_actions: [],
    },
    data_quality: {
      assessment: 'NOT_IMPLEMENTED',
      metric_eligible: null,
      reason_code: 'METRIC_ELIGIBILITY_NOT_IMPLEMENTED',
      unavailable_sections: ['METRICS', 'OPPORTUNITIES', 'RETEST'],
    },
    as_of: asOf,
  };
}
export { asOf, batch, batchId, detail, run, runId, summary };
