"""回答级指标与公共读模型共享的闭合样本/排除值；公式仍由服务拥有。"""

from enum import StrEnum


class SampleLevel(StrEnum):
    NONE = "NONE"
    OBSERVED = "OBSERVED"
    REPORTABLE = "REPORTABLE"
    STABLE = "STABLE"


class MetricExclusion(StrEnum):
    RUN_NOT_COMPLETED = "RUN_NOT_COMPLETED"
    ANSWER_MISSING_OR_EMPTY = "ANSWER_MISSING_OR_EMPTY"
    CURRENT_ANALYSIS_UNAVAILABLE = "CURRENT_ANALYSIS_UNAVAILABLE"
    CURRENT_REVIEW_REQUIRED = "CURRENT_REVIEW_REQUIRED"
    INTEGRITY_ERROR = "INTEGRITY_ERROR"
    ADMINISTRATOR_EXCLUDED = "ADMINISTRATOR_EXCLUDED"
    SUPERSEDED_ATTEMPT = "SUPERSEDED_ATTEMPT"
    DIMENSION_MISMATCH = "DIMENSION_MISMATCH"
    SUBJECT_NOT_APPLICABLE = "SUBJECT_NOT_APPLICABLE"
    MENTION_MODE_NOT_APPLICABLE = "MENTION_MODE_NOT_APPLICABLE"
    INTENT_NOT_APPLICABLE = "INTENT_NOT_APPLICABLE"
    RELIABLE_ORDER_UNAVAILABLE = "RELIABLE_ORDER_UNAVAILABLE"
    TARGET_RANK_UNAVAILABLE = "TARGET_RANK_UNAVAILABLE"
    CITATION_OBSERVATION_UNAVAILABLE = "CITATION_OBSERVATION_UNAVAILABLE"
    CITATION_CLASSIFICATION_INCOMPLETE = "CITATION_CLASSIFICATION_INCOMPLETE"
    ASSESSABLE_CLAIM_UNAVAILABLE = "ASSESSABLE_CLAIM_UNAVAILABLE"
    INSUFFICIENT_REPEATS = "INSUFFICIENT_REPEATS"
