/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteRouteImport } from './routes/_app/_admin/route'
import { Route as AppContentRouteRouteImport } from './routes/_app/content/route'
import { Route as AppProductsRouteRouteImport } from './routes/_app/products/route'
import { Route as AppPublishingRouteRouteImport } from './routes/_app/publishing/route'
import { Route as AppContentTasksRouteRouteImport } from './routes/_app/content/tasks/route'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products/$productId'
import { Route as AppProductsNewRouteImport } from './routes/_app/products/new'
import { Route as AppPublishingArticlesRouteRouteImport } from './routes/_app/publishing/articles/route'
import { Route as AppPublishingWorkRouteRouteImport } from './routes/_app/publishing/work/route'
import { Route as AppAdminSystemUsersRouteImport } from './routes/_app/_admin/system.users'
import { Route as AppContentTasksIndexRouteImport } from './routes/_app/content/tasks/index'
import { Route as AppContentTasksTaskIdRouteImport } from './routes/_app/content/tasks/$taskId'
import { Route as AppContentTasksNewRouteImport } from './routes/_app/content/tasks/new'
import { Route as AppContentVersionsVersionIdRouteImport } from './routes/_app/content/versions_.$versionId'
import { Route as AppProductsProductIdFactsRouteImport } from './routes/_app/products/$productId_.facts'
import { Route as AppPublishingArticlesIndexRouteImport } from './routes/_app/publishing/articles/index'
import { Route as AppPublishingArticlesArticleIdRouteImport } from './routes/_app/publishing/articles/$articleId'
import { Route as AppPublishingWorkIndexRouteImport } from './routes/_app/publishing/work/index'
import { Route as AppPublishingWorkWorkIdRouteImport } from './routes/_app/publishing/work/$workId'
import { Route as AppContentTasksTaskIdEditorRouteImport } from './routes/_app/content/tasks/$taskId_.editor'
import { Route as AppContentTasksTaskIdReviewRouteImport } from './routes/_app/content/tasks/$taskId_.review'
import { Route as AppProductsProductIdFactsReviewRouteImport } from './routes/_app/products/$productId_.facts_.review'
import { Route as AppProductsProductIdFactsVersionsRouteImport } from './routes/_app/products/$productId_.facts_.versions'
import { Route as AppProductsProductIdFactsVersionsVersionIdRouteImport } from './routes/_app/products/$productId_.facts_.versions_.$versionId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentRouteRoute = AppContentRouteRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsRouteRoute = AppProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPublishingRouteRoute = AppPublishingRouteRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContentTasksRouteRoute = AppContentTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppContentRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppPublishingArticlesRouteRoute =
  AppPublishingArticlesRouteRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AppPublishingRouteRoute,
  } as any)
const AppPublishingWorkRouteRoute = AppPublishingWorkRouteRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppPublishingRouteRoute,
} as any)
const AppAdminSystemUsersRoute = AppAdminSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppContentTasksIndexRoute = AppContentTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContentTasksRouteRoute,
} as any)
const AppContentTasksTaskIdRoute = AppContentTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppContentTasksRouteRoute,
} as any)
const AppContentTasksNewRoute = AppContentTasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppContentTasksRouteRoute,
} as any)
const AppContentVersionsVersionIdRoute =
  AppContentVersionsVersionIdRouteImport.update({
    id: '/versions_/$versionId',
    path: '/versions/$versionId',
    getParentRoute: () => AppContentRouteRoute,
  } as any)
const AppProductsProductIdFactsRoute =
  AppProductsProductIdFactsRouteImport.update({
    id: '/$productId_/facts',
    path: '/$productId/facts',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)
const AppPublishingArticlesIndexRoute =
  AppPublishingArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPublishingArticlesRouteRoute,
  } as any)
const AppPublishingArticlesArticleIdRoute =
  AppPublishingArticlesArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AppPublishingArticlesRouteRoute,
  } as any)
const AppPublishingWorkIndexRoute = AppPublishingWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPublishingWorkRouteRoute,
} as any)
const AppPublishingWorkWorkIdRoute = AppPublishingWorkWorkIdRouteImport.update({
  id: '/$workId',
  path: '/$workId',
  getParentRoute: () => AppPublishingWorkRouteRoute,
} as any)
const AppContentTasksTaskIdEditorRoute =
  AppContentTasksTaskIdEditorRouteImport.update({
    id: '/$taskId_/editor',
    path: '/$taskId/editor',
    getParentRoute: () => AppContentTasksRouteRoute,
  } as any)
const AppContentTasksTaskIdReviewRoute =
  AppContentTasksTaskIdReviewRouteImport.update({
    id: '/$taskId_/review',
    path: '/$taskId/review',
    getParentRoute: () => AppContentTasksRouteRoute,
  } as any)
const AppProductsProductIdFactsReviewRoute =
  AppProductsProductIdFactsReviewRouteImport.update({
    id: '/$productId_/facts_/review',
    path: '/$productId/facts/review',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)
const AppProductsProductIdFactsVersionsRoute =
  AppProductsProductIdFactsVersionsRouteImport.update({
    id: '/$productId_/facts_/versions',
    path: '/$productId/facts/versions',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)
const AppProductsProductIdFactsVersionsVersionIdRoute =
  AppProductsProductIdFactsVersionsVersionIdRouteImport.update({
    id: '/$productId_/facts_/versions_/$versionId',
    path: '/$productId/facts/versions/$versionId',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/content': typeof AppContentRouteRouteWithChildren
  '/products': typeof AppProductsRouteRouteWithChildren
  '/publishing': typeof AppPublishingRouteRouteWithChildren
  '/content/tasks': typeof AppContentTasksRouteRouteWithChildren
  '/publishing/articles': typeof AppPublishingArticlesRouteRouteWithChildren
  '/publishing/work': typeof AppPublishingWorkRouteRouteWithChildren
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/products/': typeof AppProductsIndexRoute
  '/system/users': typeof AppAdminSystemUsersRoute
  '/content/tasks/$taskId': typeof AppContentTasksTaskIdRoute
  '/content/tasks/new': typeof AppContentTasksNewRoute
  '/content/versions/$versionId': typeof AppContentVersionsVersionIdRoute
  '/products/$productId/facts': typeof AppProductsProductIdFactsRoute
  '/publishing/articles/$articleId': typeof AppPublishingArticlesArticleIdRoute
  '/publishing/work/$workId': typeof AppPublishingWorkWorkIdRoute
  '/content/tasks/': typeof AppContentTasksIndexRoute
  '/publishing/articles/': typeof AppPublishingArticlesIndexRoute
  '/publishing/work/': typeof AppPublishingWorkIndexRoute
  '/content/tasks/$taskId/editor': typeof AppContentTasksTaskIdEditorRoute
  '/content/tasks/$taskId/review': typeof AppContentTasksTaskIdReviewRoute
  '/products/$productId/facts/review': typeof AppProductsProductIdFactsReviewRoute
  '/products/$productId/facts/versions': typeof AppProductsProductIdFactsVersionsRoute
  '/products/$productId/facts/versions/$versionId': typeof AppProductsProductIdFactsVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/content': typeof AppContentRouteRouteWithChildren
  '/publishing': typeof AppPublishingRouteRouteWithChildren
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/products': typeof AppProductsIndexRoute
  '/system/users': typeof AppAdminSystemUsersRoute
  '/content/tasks/$taskId': typeof AppContentTasksTaskIdRoute
  '/content/tasks/new': typeof AppContentTasksNewRoute
  '/content/versions/$versionId': typeof AppContentVersionsVersionIdRoute
  '/products/$productId/facts': typeof AppProductsProductIdFactsRoute
  '/publishing/articles/$articleId': typeof AppPublishingArticlesArticleIdRoute
  '/publishing/work/$workId': typeof AppPublishingWorkWorkIdRoute
  '/content/tasks': typeof AppContentTasksIndexRoute
  '/publishing/articles': typeof AppPublishingArticlesIndexRoute
  '/publishing/work': typeof AppPublishingWorkIndexRoute
  '/content/tasks/$taskId/editor': typeof AppContentTasksTaskIdEditorRoute
  '/content/tasks/$taskId/review': typeof AppContentTasksTaskIdReviewRoute
  '/products/$productId/facts/review': typeof AppProductsProductIdFactsReviewRoute
  '/products/$productId/facts/versions': typeof AppProductsProductIdFactsVersionsRoute
  '/products/$productId/facts/versions/$versionId': typeof AppProductsProductIdFactsVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_admin': typeof AppAdminRouteRouteWithChildren
  '/_app/content': typeof AppContentRouteRouteWithChildren
  '/_app/products': typeof AppProductsRouteRouteWithChildren
  '/_app/publishing': typeof AppPublishingRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/content/tasks': typeof AppContentTasksRouteRouteWithChildren
  '/_app/publishing/articles': typeof AppPublishingArticlesRouteRouteWithChildren
  '/_app/publishing/work': typeof AppPublishingWorkRouteRouteWithChildren
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/_admin/system/users': typeof AppAdminSystemUsersRoute
  '/_app/content/tasks/$taskId': typeof AppContentTasksTaskIdRoute
  '/_app/content/tasks/new': typeof AppContentTasksNewRoute
  '/_app/content/versions_/$versionId': typeof AppContentVersionsVersionIdRoute
  '/_app/products/$productId_/facts': typeof AppProductsProductIdFactsRoute
  '/_app/publishing/articles/$articleId': typeof AppPublishingArticlesArticleIdRoute
  '/_app/publishing/work/$workId': typeof AppPublishingWorkWorkIdRoute
  '/_app/content/tasks/': typeof AppContentTasksIndexRoute
  '/_app/publishing/articles/': typeof AppPublishingArticlesIndexRoute
  '/_app/publishing/work/': typeof AppPublishingWorkIndexRoute
  '/_app/content/tasks/$taskId_/editor': typeof AppContentTasksTaskIdEditorRoute
  '/_app/content/tasks/$taskId_/review': typeof AppContentTasksTaskIdReviewRoute
  '/_app/products/$productId_/facts_/review': typeof AppProductsProductIdFactsReviewRoute
  '/_app/products/$productId_/facts_/versions': typeof AppProductsProductIdFactsVersionsRoute
  '/_app/products/$productId_/facts_/versions_/$versionId': typeof AppProductsProductIdFactsVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/products'
    | '/publishing'
    | '/content/tasks'
    | '/publishing/articles'
    | '/publishing/work'
    | '/products/$productId'
    | '/products/new'
    | '/products/'
    | '/system/users'
    | '/content/tasks/$taskId'
    | '/content/tasks/new'
    | '/content/versions/$versionId'
    | '/products/$productId/facts'
    | '/publishing/articles/$articleId'
    | '/publishing/work/$workId'
    | '/content/tasks/'
    | '/publishing/articles/'
    | '/publishing/work/'
    | '/content/tasks/$taskId/editor'
    | '/content/tasks/$taskId/review'
    | '/products/$productId/facts/review'
    | '/products/$productId/facts/versions'
    | '/products/$productId/facts/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content'
    | '/publishing'
    | '/products/$productId'
    | '/products/new'
    | '/products'
    | '/system/users'
    | '/content/tasks/$taskId'
    | '/content/tasks/new'
    | '/content/versions/$versionId'
    | '/products/$productId/facts'
    | '/publishing/articles/$articleId'
    | '/publishing/work/$workId'
    | '/content/tasks'
    | '/publishing/articles'
    | '/publishing/work'
    | '/content/tasks/$taskId/editor'
    | '/content/tasks/$taskId/review'
    | '/products/$productId/facts/review'
    | '/products/$productId/facts/versions'
    | '/products/$productId/facts/versions/$versionId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_admin'
    | '/_app/content'
    | '/_app/products'
    | '/_app/publishing'
    | '/_app/'
    | '/_app/content/tasks'
    | '/_app/publishing/articles'
    | '/_app/publishing/work'
    | '/_app/products/$productId'
    | '/_app/products/new'
    | '/_app/products/'
    | '/_app/_admin/system/users'
    | '/_app/content/tasks/$taskId'
    | '/_app/content/tasks/new'
    | '/_app/content/versions_/$versionId'
    | '/_app/products/$productId_/facts'
    | '/_app/publishing/articles/$articleId'
    | '/_app/publishing/work/$workId'
    | '/_app/content/tasks/'
    | '/_app/publishing/articles/'
    | '/_app/publishing/work/'
    | '/_app/content/tasks/$taskId_/editor'
    | '/_app/content/tasks/$taskId_/review'
    | '/_app/products/$productId_/facts_/review'
    | '/_app/products/$productId_/facts_/versions'
    | '/_app/products/$productId_/facts_/versions_/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/content': {
      id: '/_app/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AppContentRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/publishing': {
      id: '/_app/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof AppPublishingRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/content/tasks': {
      id: '/_app/content/tasks'
      path: '/tasks'
      fullPath: '/content/tasks'
      preLoaderRoute: typeof AppContentTasksRouteRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/_app/publishing/articles': {
      id: '/_app/publishing/articles'
      path: '/articles'
      fullPath: '/publishing/articles'
      preLoaderRoute: typeof AppPublishingArticlesRouteRouteImport
      parentRoute: typeof AppPublishingRouteRoute
    }
    '/_app/publishing/work': {
      id: '/_app/publishing/work'
      path: '/work'
      fullPath: '/publishing/work'
      preLoaderRoute: typeof AppPublishingWorkRouteRouteImport
      parentRoute: typeof AppPublishingRouteRoute
    }
    '/_app/_admin/system/users': {
      id: '/_app/_admin/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AppAdminSystemUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/content/tasks/': {
      id: '/_app/content/tasks/'
      path: '/'
      fullPath: '/content/tasks/'
      preLoaderRoute: typeof AppContentTasksIndexRouteImport
      parentRoute: typeof AppContentTasksRouteRoute
    }
    '/_app/content/tasks/$taskId': {
      id: '/_app/content/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/content/tasks/$taskId'
      preLoaderRoute: typeof AppContentTasksTaskIdRouteImport
      parentRoute: typeof AppContentTasksRouteRoute
    }
    '/_app/content/tasks/new': {
      id: '/_app/content/tasks/new'
      path: '/new'
      fullPath: '/content/tasks/new'
      preLoaderRoute: typeof AppContentTasksNewRouteImport
      parentRoute: typeof AppContentTasksRouteRoute
    }
    '/_app/content/versions_/$versionId': {
      id: '/_app/content/versions_/$versionId'
      path: '/versions/$versionId'
      fullPath: '/content/versions/$versionId'
      preLoaderRoute: typeof AppContentVersionsVersionIdRouteImport
      parentRoute: typeof AppContentRouteRoute
    }
    '/_app/products/$productId_/facts': {
      id: '/_app/products/$productId_/facts'
      path: '/$productId/facts'
      fullPath: '/products/$productId/facts'
      preLoaderRoute: typeof AppProductsProductIdFactsRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/_app/publishing/articles/': {
      id: '/_app/publishing/articles/'
      path: '/'
      fullPath: '/publishing/articles/'
      preLoaderRoute: typeof AppPublishingArticlesIndexRouteImport
      parentRoute: typeof AppPublishingArticlesRouteRoute
    }
    '/_app/publishing/articles/$articleId': {
      id: '/_app/publishing/articles/$articleId'
      path: '/$articleId'
      fullPath: '/publishing/articles/$articleId'
      preLoaderRoute: typeof AppPublishingArticlesArticleIdRouteImport
      parentRoute: typeof AppPublishingArticlesRouteRoute
    }
    '/_app/publishing/work/': {
      id: '/_app/publishing/work/'
      path: '/'
      fullPath: '/publishing/work/'
      preLoaderRoute: typeof AppPublishingWorkIndexRouteImport
      parentRoute: typeof AppPublishingWorkRouteRoute
    }
    '/_app/publishing/work/$workId': {
      id: '/_app/publishing/work/$workId'
      path: '/$workId'
      fullPath: '/publishing/work/$workId'
      preLoaderRoute: typeof AppPublishingWorkWorkIdRouteImport
      parentRoute: typeof AppPublishingWorkRouteRoute
    }
    '/_app/content/tasks/$taskId_/editor': {
      id: '/_app/content/tasks/$taskId_/editor'
      path: '/$taskId/editor'
      fullPath: '/content/tasks/$taskId/editor'
      preLoaderRoute: typeof AppContentTasksTaskIdEditorRouteImport
      parentRoute: typeof AppContentTasksRouteRoute
    }
    '/_app/content/tasks/$taskId_/review': {
      id: '/_app/content/tasks/$taskId_/review'
      path: '/$taskId/review'
      fullPath: '/content/tasks/$taskId/review'
      preLoaderRoute: typeof AppContentTasksTaskIdReviewRouteImport
      parentRoute: typeof AppContentTasksRouteRoute
    }
    '/_app/products/$productId_/facts_/review': {
      id: '/_app/products/$productId_/facts_/review'
      path: '/$productId/facts/review'
      fullPath: '/products/$productId/facts/review'
      preLoaderRoute: typeof AppProductsProductIdFactsReviewRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/_app/products/$productId_/facts_/versions': {
      id: '/_app/products/$productId_/facts_/versions'
      path: '/$productId/facts/versions'
      fullPath: '/products/$productId/facts/versions'
      preLoaderRoute: typeof AppProductsProductIdFactsVersionsRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/_app/products/$productId_/facts_/versions_/$versionId': {
      id: '/_app/products/$productId_/facts_/versions_/$versionId'
      path: '/$productId/facts/versions/$versionId'
      fullPath: '/products/$productId/facts/versions/$versionId'
      preLoaderRoute: typeof AppProductsProductIdFactsVersionsVersionIdRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminSystemUsersRoute: typeof AppAdminSystemUsersRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminSystemUsersRoute: AppAdminSystemUsersRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppContentTasksRouteRouteChildren {
  AppContentTasksTaskIdRoute: typeof AppContentTasksTaskIdRoute
  AppContentTasksNewRoute: typeof AppContentTasksNewRoute
  AppContentTasksIndexRoute: typeof AppContentTasksIndexRoute
  AppContentTasksTaskIdEditorRoute: typeof AppContentTasksTaskIdEditorRoute
  AppContentTasksTaskIdReviewRoute: typeof AppContentTasksTaskIdReviewRoute
}

const AppContentTasksRouteRouteChildren: AppContentTasksRouteRouteChildren = {
  AppContentTasksTaskIdRoute: AppContentTasksTaskIdRoute,
  AppContentTasksNewRoute: AppContentTasksNewRoute,
  AppContentTasksIndexRoute: AppContentTasksIndexRoute,
  AppContentTasksTaskIdEditorRoute: AppContentTasksTaskIdEditorRoute,
  AppContentTasksTaskIdReviewRoute: AppContentTasksTaskIdReviewRoute,
}

const AppContentTasksRouteRouteWithChildren =
  AppContentTasksRouteRoute._addFileChildren(AppContentTasksRouteRouteChildren)

interface AppContentRouteRouteChildren {
  AppContentTasksRouteRoute: typeof AppContentTasksRouteRouteWithChildren
  AppContentVersionsVersionIdRoute: typeof AppContentVersionsVersionIdRoute
}

const AppContentRouteRouteChildren: AppContentRouteRouteChildren = {
  AppContentTasksRouteRoute: AppContentTasksRouteRouteWithChildren,
  AppContentVersionsVersionIdRoute: AppContentVersionsVersionIdRoute,
}

const AppContentRouteRouteWithChildren = AppContentRouteRoute._addFileChildren(
  AppContentRouteRouteChildren,
)

interface AppProductsRouteRouteChildren {
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProductsProductIdFactsRoute: typeof AppProductsProductIdFactsRoute
  AppProductsProductIdFactsReviewRoute: typeof AppProductsProductIdFactsReviewRoute
  AppProductsProductIdFactsVersionsRoute: typeof AppProductsProductIdFactsVersionsRoute
  AppProductsProductIdFactsVersionsVersionIdRoute: typeof AppProductsProductIdFactsVersionsVersionIdRoute
}

const AppProductsRouteRouteChildren: AppProductsRouteRouteChildren = {
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProductsProductIdFactsRoute: AppProductsProductIdFactsRoute,
  AppProductsProductIdFactsReviewRoute: AppProductsProductIdFactsReviewRoute,
  AppProductsProductIdFactsVersionsRoute:
    AppProductsProductIdFactsVersionsRoute,
  AppProductsProductIdFactsVersionsVersionIdRoute:
    AppProductsProductIdFactsVersionsVersionIdRoute,
}

const AppProductsRouteRouteWithChildren =
  AppProductsRouteRoute._addFileChildren(AppProductsRouteRouteChildren)

interface AppPublishingArticlesRouteRouteChildren {
  AppPublishingArticlesArticleIdRoute: typeof AppPublishingArticlesArticleIdRoute
  AppPublishingArticlesIndexRoute: typeof AppPublishingArticlesIndexRoute
}

const AppPublishingArticlesRouteRouteChildren: AppPublishingArticlesRouteRouteChildren =
  {
    AppPublishingArticlesArticleIdRoute: AppPublishingArticlesArticleIdRoute,
    AppPublishingArticlesIndexRoute: AppPublishingArticlesIndexRoute,
  }

const AppPublishingArticlesRouteRouteWithChildren =
  AppPublishingArticlesRouteRoute._addFileChildren(
    AppPublishingArticlesRouteRouteChildren,
  )

interface AppPublishingWorkRouteRouteChildren {
  AppPublishingWorkWorkIdRoute: typeof AppPublishingWorkWorkIdRoute
  AppPublishingWorkIndexRoute: typeof AppPublishingWorkIndexRoute
}

const AppPublishingWorkRouteRouteChildren: AppPublishingWorkRouteRouteChildren =
  {
    AppPublishingWorkWorkIdRoute: AppPublishingWorkWorkIdRoute,
    AppPublishingWorkIndexRoute: AppPublishingWorkIndexRoute,
  }

const AppPublishingWorkRouteRouteWithChildren =
  AppPublishingWorkRouteRoute._addFileChildren(
    AppPublishingWorkRouteRouteChildren,
  )

interface AppPublishingRouteRouteChildren {
  AppPublishingArticlesRouteRoute: typeof AppPublishingArticlesRouteRouteWithChildren
  AppPublishingWorkRouteRoute: typeof AppPublishingWorkRouteRouteWithChildren
}

const AppPublishingRouteRouteChildren: AppPublishingRouteRouteChildren = {
  AppPublishingArticlesRouteRoute: AppPublishingArticlesRouteRouteWithChildren,
  AppPublishingWorkRouteRoute: AppPublishingWorkRouteRouteWithChildren,
}

const AppPublishingRouteRouteWithChildren =
  AppPublishingRouteRoute._addFileChildren(AppPublishingRouteRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppContentRouteRoute: typeof AppContentRouteRouteWithChildren
  AppProductsRouteRoute: typeof AppProductsRouteRouteWithChildren
  AppPublishingRouteRoute: typeof AppPublishingRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppContentRouteRoute: AppContentRouteRouteWithChildren,
  AppProductsRouteRoute: AppProductsRouteRouteWithChildren,
  AppPublishingRouteRoute: AppPublishingRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
