/** AI 渠道面板集中管理连接、Header 与模型，不持有平台配置职责。 */
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Alert, Button, Card, Form, Input, InputNumber, Modal, Select, Space, Table, Typography } from 'antd';
import { useState } from 'react';
import { queryClient } from '../../app/queryClient';
import { api, csrfHeader, ensureSuccess, errorMessage, unwrap } from '../../shared/api/client';
import { queryKeys } from '../../shared/api/queryKeys';
import type { AIChannel, AIModel, Schema } from '../../shared/api/types';
import { StatusTag } from '../../shared/components/StatusTag';

export function AIChannelsPanel() {
  const [createOpen, setCreateOpen] = useState(false);
  const [selected, setSelected] = useState<AIChannel>();
  const channels = useQuery({ queryKey: queryKeys.aiChannels.all, queryFn: async () => unwrap(await api.GET('/api/v1/ai-channels')) });
  const refresh = async () => queryClient.invalidateQueries({ queryKey: queryKeys.aiChannels.all });
  const create = useMutation({ mutationFn: async (body: Schema<'AIChannelCreate'>) => unwrap(await api.POST('/api/v1/ai-channels', { params: { header: csrfHeader() }, body })), onSuccess: async () => { setCreateOpen(false); await refresh(); } });
  const toggle = useMutation({ mutationFn: async (channel: AIChannel) => { const path = channel.is_enabled ? '/api/v1/ai-channels/{channel_id}/disable' as const : '/api/v1/ai-channels/{channel_id}/enable' as const; return unwrap(await api.POST(path, { params: { path: { channel_id: channel.id }, header: csrfHeader() }, body: { expected_revision: channel.revision } })); }, onSuccess: refresh });
  const remove = useMutation({ mutationFn: async (channel: AIChannel) => ensureSuccess(await api.DELETE('/api/v1/ai-channels/{channel_id}', { params: { path: { channel_id: channel.id }, header: csrfHeader() } })), onSuccess: refresh });
  const error = channels.error ?? create.error ?? toggle.error ?? remove.error;
  return <Card extra={<Button type="primary" icon={<PlusOutlined />} onClick={() => setCreateOpen(true)}>新增渠道</Button>}>{error && <Alert type="error" message={errorMessage(error)} />}<Table<AIChannel> rowKey="id" loading={channels.isLoading} dataSource={channels.data?.items} columns={[{ title: '渠道', dataIndex: 'name' }, { title: 'API 根地址', dataIndex: 'base_url' }, { title: '超时', dataIndex: 'timeout_seconds', render: (value) => `${value}s` }, { title: '状态', dataIndex: 'is_enabled', render: (value) => <StatusTag status={value ? 'ACTIVE' : 'RETIRED'} /> }, { title: '操作', render: (_, row) => <Space wrap><Button size="small" onClick={() => setSelected(row)}>Header 与模型</Button><Button size="small" onClick={() => toggle.mutate(row)}>{row.is_enabled ? '停用' : '启用'}</Button><Button size="small" danger icon={<DeleteOutlined />} onClick={() => remove.mutate(row)}>删除</Button></Space> }]} />
    <Modal title="新增 AI 渠道" open={createOpen} onCancel={() => setCreateOpen(false)} footer={null} destroyOnHidden><Form<Schema<'AIChannelCreate'>> layout="vertical" initialValues={{ timeout_seconds: 60 }} onFinish={(body) => create.mutate(body)}><Form.Item name="name" label="渠道名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="base_url" label="API 根地址" rules={[{ required: true, type: 'url' }]}><Input placeholder="https://provider.example/v1" /></Form.Item><Form.Item name="api_key" label="API Key" rules={[{ required: true }]}><Input.Password /></Form.Item><Form.Item name="timeout_seconds" label="超时秒数" rules={[{ required: true }]}><InputNumber min={10} max={600} /></Form.Item><Button type="primary" htmlType="submit" loading={create.isPending}>创建</Button></Form></Modal>
    <Modal title={selected?.name ?? '渠道详情'} open={!!selected} onCancel={() => setSelected(undefined)} footer={null} width={960} destroyOnHidden>{selected && <ChannelDetail channelId={selected.id} />}</Modal>
  </Card>;
}

function ChannelDetail({ channelId }: { channelId: string }) {
  const [headerOpen, setHeaderOpen] = useState(false);
  const [modelOpen, setModelOpen] = useState(false);
  const [editingHeader, setEditingHeader] = useState<Schema<'AIChannelHeader'>>();
  const [editingModel, setEditingModel] = useState<AIModel>();
  const [discovered, setDiscovered] = useState<string[]>([]);
  const [discoveredModelId, setDiscoveredModelId] = useState<string>();
  const channel = useQuery({ queryKey: queryKeys.aiChannels.detail(channelId), queryFn: async () => unwrap(await api.GET('/api/v1/ai-channels/{channel_id}', { params: { path: { channel_id: channelId } } })) });
  const models = useQuery({ queryKey: queryKeys.aiChannels.models(channelId), queryFn: async () => unwrap(await api.GET('/api/v1/ai-channels/{channel_id}/models', { params: { path: { channel_id: channelId } } })) });
  const refresh = async () => Promise.all([queryClient.invalidateQueries({ queryKey: queryKeys.aiChannels.detail(channelId) }), queryClient.invalidateQueries({ queryKey: queryKeys.aiChannels.models(channelId) }), queryClient.invalidateQueries({ queryKey: queryKeys.aiChannels.all })]);
  const discover = useMutation({ mutationFn: async () => unwrap(await api.POST('/api/v1/ai-channels/{channel_id}/discover-models', { params: { path: { channel_id: channelId }, header: csrfHeader() } })), onSuccess: (data) => setDiscovered(data.items.map((item) => item.model_id)) });
  const addHeader = useMutation({ mutationFn: async (body: Omit<Schema<'AIChannelHeaderCreate'>, 'expected_channel_revision'>) => { if (!channel.data) throw new Error('渠道未加载'); return unwrap(await api.POST('/api/v1/ai-channels/{channel_id}/headers', { params: { path: { channel_id: channelId }, header: csrfHeader() }, body: { ...body, expected_channel_revision: channel.data.revision } })); }, onSuccess: async () => { setHeaderOpen(false); await refresh(); } });
  const updateHeader = useMutation({ mutationFn: async (body: Omit<Schema<'AIChannelHeaderUpdate'>, 'expected_channel_revision'>) => { if (!channel.data || !editingHeader) throw new Error('Header 未加载'); return unwrap(await api.PATCH('/api/v1/ai-channel-headers/{header_id}', { params: { path: { header_id: editingHeader.id }, header: csrfHeader() }, body: { ...body, expected_channel_revision: channel.data.revision } })); }, onSuccess: async () => { setEditingHeader(undefined); await refresh(); } });
  const deleteHeader = useMutation({ mutationFn: async (headerId: string) => ensureSuccess(await api.DELETE('/api/v1/ai-channel-headers/{header_id}', { params: { path: { header_id: headerId }, header: csrfHeader() } })), onSuccess: refresh });
  const createModel = useMutation({ mutationFn: async (values: { display_name: string; model_id: string; request_parameters_json: string }) => { const parsed: unknown = JSON.parse(values.request_parameters_json || '{}'); if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error('请求参数必须是 JSON 对象'); return unwrap(await api.POST('/api/v1/ai-channels/{channel_id}/models', { params: { path: { channel_id: channelId }, header: csrfHeader() }, body: { display_name: values.display_name, model_id: values.model_id, request_parameters: parsed as Record<string, unknown> } })); }, onSuccess: async () => { setModelOpen(false); setDiscoveredModelId(undefined); await refresh(); } });
  const updateModel = useMutation({ mutationFn: async (values: { display_name: string; model_id: string; request_parameters_json: string }) => { if (!editingModel) throw new Error('模型未加载'); const parsed: unknown = JSON.parse(values.request_parameters_json || '{}'); if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error('请求参数必须是 JSON 对象'); return unwrap(await api.PATCH('/api/v1/ai-models/{model_id}', { params: { path: { model_id: editingModel.id }, header: csrfHeader() }, body: { expected_revision: editingModel.revision, display_name: values.display_name, model_id: values.model_id, request_parameters: parsed as Record<string, unknown> } })); }, onSuccess: async () => { setEditingModel(undefined); await refresh(); } });
  const updateChannel = useMutation({ mutationFn: async (body: { name: string; base_url: string; timeout_seconds: number }) => { if (!channel.data) throw new Error('渠道未加载'); return unwrap(await api.PATCH('/api/v1/ai-channels/{channel_id}', { params: { path: { channel_id: channelId }, header: csrfHeader() }, body: { ...body, expected_revision: channel.data.revision } })); }, onSuccess: refresh });
  const replaceKey = useMutation({ mutationFn: async (body: { api_key: string }) => { if (!channel.data) throw new Error('渠道未加载'); return unwrap(await api.PUT('/api/v1/ai-channels/{channel_id}/api-key', { params: { path: { channel_id: channelId }, header: csrfHeader() }, body: { ...body, expected_revision: channel.data.revision } })); }, onSuccess: refresh });
  const testModel = useMutation({ mutationFn: async (model: AIModel) => unwrap(await api.POST('/api/v1/ai-models/{model_id}/test', { params: { path: { model_id: model.id }, header: csrfHeader() } })), onSuccess: refresh });
  const toggleModel = useMutation({ mutationFn: async (model: AIModel) => { const path = model.is_enabled ? '/api/v1/ai-models/{model_id}/disable' as const : '/api/v1/ai-models/{model_id}/enable' as const; return unwrap(await api.POST(path, { params: { path: { model_id: model.id }, header: csrfHeader() }, body: { expected_revision: model.revision } })); }, onSuccess: refresh });
  const deleteModel = useMutation({ mutationFn: async (model: AIModel) => ensureSuccess(await api.DELETE('/api/v1/ai-models/{model_id}', { params: { path: { model_id: model.id }, header: csrfHeader() } })), onSuccess: refresh });
  const error = channel.error ?? models.error ?? discover.error ?? addHeader.error ?? updateHeader.error ?? deleteHeader.error ?? createModel.error ?? updateModel.error ?? updateChannel.error ?? replaceKey.error ?? testModel.error ?? toggleModel.error ?? deleteModel.error;
  return <Space direction="vertical" size="large" style={{ width: '100%' }}>{error && <Alert type="error" message={errorMessage(error)} />}{channel.data && <Card title="连接配置"><Form<{ name: string; base_url: string; timeout_seconds: number }> layout="inline" initialValues={{ name: channel.data.name, base_url: channel.data.base_url, timeout_seconds: channel.data.timeout_seconds }} onFinish={(body) => updateChannel.mutate(body)}><Form.Item name="name" label="名称"><Input /></Form.Item><Form.Item name="base_url" label="API 根地址"><Input style={{ width: 300 }} /></Form.Item><Form.Item name="timeout_seconds" label="超时"><InputNumber min={10} max={600} /></Form.Item><Button htmlType="submit">更新连接</Button></Form><Form<{ api_key: string }> layout="inline" style={{ marginTop: 16 }} onFinish={(body) => replaceKey.mutate(body)}><Form.Item name="api_key" label="替换 API Key" rules={[{ required: true }]}><Input.Password /></Form.Item><Button htmlType="submit">替换并重置测试</Button></Form></Card>}<Card title="渠道 Header" extra={<Button icon={<PlusOutlined />} onClick={() => setHeaderOpen(true)}>新增 Header</Button>}><Table rowKey="id" dataSource={channel.data?.headers} pagination={false} columns={[{ title: '名称', dataIndex: 'name' }, { title: '类型', dataIndex: 'is_sensitive', render: (value) => value ? '敏感' : '普通' }, { title: '值', dataIndex: 'value', render: (value, row) => row.is_sensitive ? '已加密配置' : value }, { title: '操作', render: (_, row) => <Space><Button size="small" onClick={() => setEditingHeader(row)}>编辑</Button><Button size="small" danger onClick={() => deleteHeader.mutate(row.id)}>删除</Button></Space> }]} /></Card><Card title="模型" extra={<Space><Button onClick={() => discover.mutate()} loading={discover.isPending}>获取模型</Button><Button type="primary" onClick={() => { setDiscoveredModelId(undefined); setModelOpen(true); }}>手工添加</Button></Space>}><Typography.Paragraph type="secondary">远端发现结果不会自动创建模型，请选择后确认保存。</Typography.Paragraph><Space wrap>{discovered.length > 0 ? discovered.map((modelId) => <Button size="small" key={modelId} onClick={() => { setDiscoveredModelId(modelId); setModelOpen(true); }}>{modelId}</Button>) : <Typography.Text type="secondary">尚未获取</Typography.Text>}</Space><Table<AIModel> rowKey="id" dataSource={models.data?.items} columns={[{ title: '显示名', dataIndex: 'display_name' }, { title: 'model_id', dataIndex: 'model_id' }, { title: '测试', dataIndex: 'test_status', render: (value) => <StatusTag status={value} /> }, { title: '状态', dataIndex: 'is_enabled', render: (value) => <StatusTag status={value ? 'ACTIVE' : 'RETIRED'} /> }, { title: '操作', render: (_, row) => <Space><Button size="small" onClick={() => setEditingModel(row)}>编辑</Button><Button size="small" onClick={() => testModel.mutate(row)}>测试</Button><Button size="small" onClick={() => toggleModel.mutate(row)}>{row.is_enabled ? '停用' : '启用'}</Button><Button size="small" danger onClick={() => deleteModel.mutate(row)}>删除</Button></Space> }]} /></Card>
    <Modal title={editingHeader ? '编辑 Header' : '新增 Header'} open={headerOpen || !!editingHeader} onCancel={() => { setHeaderOpen(false); setEditingHeader(undefined); }} footer={null} destroyOnHidden><Form<Omit<Schema<'AIChannelHeaderCreate'>, 'expected_channel_revision'>> key={editingHeader?.id ?? 'new'} layout="vertical" initialValues={{ name: editingHeader?.name, value: editingHeader?.value ?? '', is_sensitive: editingHeader?.is_sensitive ?? false }} onFinish={(body) => editingHeader ? updateHeader.mutate(body) : addHeader.mutate(body)}><Form.Item name="name" label="Header 名" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="value" label="值" rules={[{ required: true }]}><Input.Password /></Form.Item><Form.Item name="is_sensitive" label="类型"><Select options={[{ value: false, label: '普通' }, { value: true, label: '敏感且永不回显' }]} /></Form.Item><Button type="primary" htmlType="submit">保存</Button></Form></Modal>
    <Modal title={editingModel ? '编辑模型' : '添加模型'} open={modelOpen || !!editingModel} onCancel={() => { setModelOpen(false); setEditingModel(undefined); setDiscoveredModelId(undefined); }} footer={null} destroyOnHidden><Form<{ display_name: string; model_id: string; request_parameters_json: string }> key={editingModel?.id ?? discoveredModelId ?? 'new'} layout="vertical" initialValues={{ display_name: editingModel?.display_name ?? discoveredModelId, model_id: editingModel?.model_id ?? discoveredModelId, request_parameters_json: JSON.stringify(editingModel?.request_parameters ?? {}, null, 2) }} onFinish={(body) => editingModel ? updateModel.mutate(body) : createModel.mutate(body)}><Form.Item name="display_name" label="显示名" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="model_id" label="model_id" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="request_parameters_json" label="自定义请求参数 JSON"><Input.TextArea rows={6} /></Form.Item><Button type="primary" htmlType="submit">保存</Button></Form></Modal>
  </Space>;
}
