/** 平台类型面板负责类型和普通 Markdown Prompt 配置。 */
import { PlusOutlined } from '@ant-design/icons';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Alert, Button, Card, Form, Input, Modal, Space, Table } from 'antd';
import { useState } from 'react';
import { queryClient } from '../../app/queryClient';
import { api, csrfHeader, ensureSuccess, errorMessage, unwrap } from '../../shared/api/client';
import { queryKeys } from '../../shared/api/queryKeys';
import type { PlatformType, Schema } from '../../shared/api/types';

export function PlatformTypesPanel() {
  const [open, setOpen] = useState(false);
  const [editingType, setEditingType] = useState<PlatformType>();
  const [selected, setSelected] = useState<PlatformType>();
  const types = useQuery({ queryKey: queryKeys.platformTypes.all, queryFn: async () => unwrap(await api.GET('/api/v1/platform-types')) });
  const prompt = useQuery({ queryKey: queryKeys.platformTypes.prompt(selected?.id), queryFn: async () => unwrap(await api.GET('/api/v1/platform-types/{platform_type_id}/prompt', { params: { path: { platform_type_id: selected?.id ?? '' } } })), enabled: !!selected, retry: false });
  const refresh = async () => queryClient.invalidateQueries({ queryKey: queryKeys.platformTypes.all });
  const create = useMutation({ mutationFn: async (body: Schema<'PlatformTypeCreate'>) => unwrap(await api.POST('/api/v1/platform-types', { params: { header: csrfHeader() }, body })), onSuccess: async () => { setOpen(false); await refresh(); } });
  const update = useMutation({ mutationFn: async (body: Schema<'PlatformTypeCreate'>) => { if (!editingType) throw new Error('未选择平台类型'); return unwrap(await api.PATCH('/api/v1/platform-types/{platform_type_id}', { params: { path: { platform_type_id: editingType.id }, header: csrfHeader() }, body: { ...body, expected_revision: editingType.revision } })); }, onSuccess: async () => { setEditingType(undefined); await refresh(); } });
  const savePrompt = useMutation({ mutationFn: async (body: { template_markdown: string }) => { if (!selected) throw new Error('未选择平台类型'); return unwrap(await api.PUT('/api/v1/platform-types/{platform_type_id}/prompt', { params: { path: { platform_type_id: selected.id }, header: csrfHeader() }, body: { template_markdown: body.template_markdown, expected_revision: prompt.data?.revision ?? null } })); }, onSuccess: async () => queryClient.invalidateQueries({ queryKey: queryKeys.platformTypes.prompt(selected?.id) }) });
  const deletePrompt = useMutation({ mutationFn: async () => { if (!selected) throw new Error('未选择平台类型'); return ensureSuccess(await api.DELETE('/api/v1/platform-types/{platform_type_id}/prompt', { params: { path: { platform_type_id: selected.id }, header: csrfHeader() } })); }, onSuccess: async () => queryClient.invalidateQueries({ queryKey: queryKeys.platformTypes.prompt(selected?.id) }) });
  const remove = useMutation({ mutationFn: async (row: PlatformType) => ensureSuccess(await api.DELETE('/api/v1/platform-types/{platform_type_id}', { params: { path: { platform_type_id: row.id }, header: csrfHeader() } })), onSuccess: refresh });
  const error = types.error ?? create.error ?? update.error ?? savePrompt.error ?? deletePrompt.error ?? remove.error;
  return <Card extra={<Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>新增类型</Button>}>{error && <Alert type="error" message={errorMessage(error)} />}<Table<PlatformType> rowKey="id" dataSource={types.data?.items} columns={[{ title: '名称', dataIndex: 'name' }, { title: 'Slug', dataIndex: 'slug' }, { title: '操作', render: (_, row) => <Space><Button size="small" onClick={() => setEditingType(row)}>编辑类型</Button><Button size="small" onClick={() => setSelected(row)}>编辑 Prompt</Button><Button size="small" danger onClick={() => remove.mutate(row)}>删除</Button></Space> }]} /><Modal title={editingType ? '编辑平台类型' : '新增平台类型'} open={open || !!editingType} onCancel={() => { setOpen(false); setEditingType(undefined); }} footer={null} destroyOnHidden><Form<Schema<'PlatformTypeCreate'>> key={editingType?.id ?? 'new'} layout="vertical" initialValues={{ name: editingType?.name, slug: editingType?.slug }} onFinish={(body) => editingType ? update.mutate(body) : create.mutate(body)}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="slug" label="Slug" rules={[{ required: true, pattern: /^[a-z0-9-]+$/ }]}><Input /></Form.Item><Button type="primary" htmlType="submit">保存</Button></Form></Modal><Modal title={`${selected?.name ?? ''} Prompt`} open={!!selected} onCancel={() => setSelected(undefined)} footer={null} width={820} destroyOnHidden>{selected && <Form<{ template_markdown: string }> key={`${selected.id}-${prompt.data?.revision ?? 'new'}`} layout="vertical" initialValues={{ template_markdown: prompt.data?.template_markdown ?? '' }} onFinish={(body) => savePrompt.mutate(body)}><Alert type="info" showIcon message="这是普通 Markdown system Prompt，不解析变量、循环或条件。" /><Form.Item name="template_markdown" label="Prompt Markdown" rules={[{ required: true }]}><Input.TextArea rows={20} className="markdown-source" /></Form.Item><Space><Button type="primary" htmlType="submit">保存</Button>{prompt.data && <Button danger onClick={() => deletePrompt.mutate()}>删除当前 Prompt</Button>}</Space></Form>}</Modal></Card>;
}
