import type { ReactNode } from 'react';
import { TableShell } from '@/design-system/data-table/table-shell';
import { formatPoints, formatRate, formatTime, metricLabels, sampleLabels, exclusionLabels } from '@/domains/geo-insights/insights.model';
import type { Report } from './reports.model';
type Metric = Report['insights']['current_cells'][number]['metrics'][number] | Report['insights']['data_quality']['overview']['cards'][number];
function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className="min-w-0 space-y-3 border-t border-border-subtle pt-4"><h2 className="type-section-title">{title}</h2>{children}</section>;
}
function MetricTable({ title, metrics }: { title: string; metrics: Metric[] }) {
  return <TableShell regionLabel={title} className="geo-report-table-region"><thead><tr><th scope="col">指标</th><th scope="col">值</th><th scope="col">分子 / 分母</th><th scope="col">样本与排除</th><th scope="col">公式版本</th></tr></thead><tbody>{metrics.map((m) => <tr key={m.metric_code}><th scope="row">{metricLabels[m.metric_code]}</th><td>{formatRate(m.value)}</td><td>{m.numerator} / {m.denominator}</td><td>{sampleLabels[m.sample_level]}；合格 {m.eligible_run_count}；排除 {m.excluded_run_count}；不可判断声明 {m.unjudgeable_claim_count}<ul>{m.exclusion_reason_counts.map((r) => <li key={r.code}>{exclusionLabels[r.code]} {r.run_count}</li>)}</ul></td><td>{m.formula_version}{m.unavailable_reason && <p>无可用分母</p>}</td></tr>)}</tbody></TableShell>;
}
export function ReportContent({ report }: { report: Report }) {
  const i = report.insights; const quality = i.data_quality.overview;
  return <article className="geo-answer-report min-w-0 space-y-5" aria-label="回答级 GEO 报告内容">
    <header className="space-y-2"><h2 className="type-section-title">报告范围与时间</h2><p>实时报告 · 重新读取会使用当前有效分析与复核，不代表归档快照。</p><p>数据截止 as_of：{formatTime(report.as_of)}</p><p>生成时间：{formatTime(report.generated_at)}</p>
      <dl className="grid min-w-0 gap-2 text-sm sm:grid-cols-2">{Object.entries(report.filters).map(([key, value]) => <div key={key} className="min-w-0 break-all"><dt className="font-medium">{key}</dt><dd>{value === null || Array.isArray(value) && value.length === 0 ? '全部 / 未限定' : Array.isArray(value) ? value.join(', ') : String(value)}</dd></div>)}</dl>
    </header>
    {!report.available && <div role="status" className="rounded-md border border-warning p-4"><p className="font-medium">报告不可用</p><p>{report.unavailable_reason === 'NO_DATA' ? '当前筛选没有运行数据，不能生成成功报告。' : '当前筛选没有合格运行；请查看数据质量和排除原因。'}</p></div>}
    <Section title="运行与数据质量"><p>候选运行 {quality.candidate_run_count} · 合格运行 {quality.eligible_run_count} · 排除运行 {quality.excluded_run_count} · 独立维度 {quality.dimension_count}</p><p>状态：{Object.entries(quality.status_counts).map(([key, value]) => `${key} ${value}`).join('；') || '无运行'}</p><MetricTable title="报告数据质量指标" metrics={quality.cards}/>
      <ul>{quality.exclusion_reason_counts.map((r) => <li key={r.code}>{exclusionLabels[r.code]}：{r.run_count}</li>)}</ul><p>共享域名：{i.data_quality.shared_domain_run_count} 个运行 / {i.data_quality.shared_domain_citation_count} 条引用</p><p>质量说明：{i.data_quality.notes.join('；') || '无附加质量提示'}</p>
      <TableShell regionLabel="报告费用与覆盖" className="geo-report-table-region"><thead><tr><th scope="col">币种</th><th scope="col">已报告运行</th><th scope="col">已知总费用</th><th scope="col">已知平均费用</th></tr></thead><tbody>{i.data_quality.known_costs.map((c) => <tr key={c.currency}><th scope="row">{c.currency}</th><td>{c.known_run_count}</td><td>{c.total_amount}</td><td>{c.average_amount}</td></tr>)}</tbody></TableShell>
      {(['collection_versions', 'analysis_versions'] as const).map((key) => <div key={key}><h3 className="type-label">{key === 'collection_versions' ? '采集版本分布' : '分析版本分布'}</h3>{i.data_quality[key].map((v) => <p key={v.version_key} className="break-all text-sm">{v.source_model ?? '模型未知'} / {v.source_product ?? '产品未知'} / {v.source_version ?? '版本未知'}；分析 {v.analyzer_version ?? '未知'} / {v.rule_set_version ?? '未知'} / {v.analysis_configuration_key ?? '未知'}；运行 {v.run_count}</p>)}</div>)}
    </Section>
    {report.available && <>
      {([['当前周期', i.current_cells], ['前周期', i.previous_cells]] as const).map(([label, cells]) => <Section key={label} title={`${label}指标、产品与平台矩阵、竞品 SOV`}>
        {cells.length === 0 && <p>无该周期样本</p>}{cells.map((c) => <section key={c.cell_key} className="min-w-0 space-y-3"><h3 className="type-label">{c.display_name}</h3><p className="break-all text-sm">对象 {c.subject_id} · 产品 {c.product_id ?? '非产品对象'} · 竞争集合 {c.sov_subject_ids.join(', ')}</p><dl className="grid min-w-0 gap-2 text-xs sm:grid-cols-3">{Object.entries(c.dimensions).map(([key, value]) => <div key={key} className="min-w-0 break-all"><dt className="font-medium">{key}</dt><dd>{value === null ? '未知' : typeof value === 'object' ? JSON.stringify(value) : String(value)}</dd></div>)}</dl><MetricTable title={`${label}${c.display_name}指标 ${c.cell_key}`} metrics={c.metrics}/></section>)}
      </Section>)}
      <Section title="趋势与前期比较"><p>当前 {formatTime(i.current_window.date_from)} ～ {formatTime(i.current_window.date_to)}；前期 {formatTime(i.previous_window.date_from)} ～ {formatTime(i.previous_window.date_to)}</p><TableShell regionLabel="报告趋势表" className="geo-report-table-region"><thead><tr><th scope="col">对象 / 问题 / 配置</th><th scope="col">指标与变化</th><th scope="col">可比性与样本</th></tr></thead><tbody>{i.trends.map((t) => <tr key={`${t.subject_id}/${t.prompt_variant_id}/${t.collection_profile_id}/${t.metric_code}`}><th scope="row" className="break-all">{t.subject_id}<br/>{t.prompt_variant_id}<br/>{t.collection_profile_id}</th><td>{metricLabels[t.metric_code]}：{formatPoints(t.change_points)}<br/>相对变化 {t.relative_change === null ? '不可比较' : formatRate(t.relative_change)}</td><td>最低运行数 {t.minimum_run_count}<br/>{t.unavailable_reasons.join('；') || '可比较'}<br/>{t.version_warnings.join('；')}<br/>{t.changed_dimensions.join('；')}</td></tr>)}</tbody></TableShell></Section>
      <Section title="问题覆盖">{i.question_coverage.map((q) => <div key={`${q.subject_id}/${q.stratum_key}`} className="break-all text-sm"><p>对象 {q.subject_id} · 目标覆盖 {formatRate(q.target_topic_coverage)}（{q.numerator} / {q.monitored_denominator}） · 正向覆盖 {formatRate(q.positive_topic_coverage)}（{q.numerator} / {q.eligible_denominator}）</p><p>目标阈值 {formatRate(q.target_rate)}；可报告门槛 {q.reportable_minimum}；稳定门槛 {q.stable_minimum}</p><ul>{q.variant_results.map((v) => <li key={v.cell_key}>{v.cell_key}：{v.classification ?? v.unavailable_reason}；{v.target_reached ? '达到目标' : '未达到目标'}</li>)}</ul></div>)}</Section>
      <Section title="主要引用来源">{i.citation_insights.map((c) => <div key={c.cell_key} className="min-w-0"><p className="break-all">对象 {c.subject_id} · 引用事件 {c.citation_count}</p>{([['域名', c.domains], ['URL', c.urls], ['类别', c.source_categories]] as const).map(([label, buckets]) => <TableShell key={label} regionLabel={`报告引用${label} ${c.cell_key}`} className="geo-report-table-region"><thead><tr><th scope="col">{label}</th><th scope="col">事件 / 运行</th><th scope="col">覆盖 / 份额</th></tr></thead><tbody>{buckets.map((b) => <tr key={b.key}><th scope="row" className="break-all">{b.key}</th><td>{b.citation_count} / {b.run_count}</td><td>{formatRate(b.coverage_value)}（{b.run_count} / {b.coverage_denominator}）；{formatRate(b.share_value)}（{b.citation_count} / {b.share_denominator}）</td></tr>)}</tbody></TableShell>)}</div>)}</Section>
      <Section title="事实风险">{i.fact_risks.map((r) => <div key={r.cell_key} className="min-w-0"><p className="break-all">对象 {r.subject_id} · 声明 {r.claim_count} · {Object.entries(r.verdict_counts).map(([key, value]) => `${key} ${value}`).join('；')}</p><p>错误严重度：{Object.entries(r.incorrect_severity_counts).map(([key, value]) => `${key} ${value}`).join('；')}</p><ul>{r.groups.map((g) => <li key={`${g.claim_kind}/${g.verdict}/${g.severity}`}>{g.claim_kind} / {g.verdict} / {g.severity}：声明 {g.claim_count} / 运行 {g.run_count}</li>)}</ul></div>)}</Section>
    </>}
    <Section title="机会"><p>机会数据尚未实现（NOT_IMPLEMENTED），当前报告不包含机会数量或行动结论。</p></Section>
    <Section title="公式与方法说明"><ul>{report.method_notes.map((note) => <li key={note}>{note}</li>)}</ul><TableShell regionLabel="报告公式字典" className="geo-report-table-region"><thead><tr><th scope="col">指标</th><th scope="col">分子</th><th scope="col">分母</th><th scope="col">版本</th></tr></thead><tbody>{report.formulas.map((f) => <tr key={f.metric_code}><th scope="row">{f.label}</th><td>{f.numerator_description}</td><td>{f.denominator_description}</td><td>{f.formula_version}</td></tr>)}</tbody></TableShell></Section>
  </article>;
}
