import { act, fireEvent, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeAll, describe, expect, it, vi } from 'vitest';
import { advancePrincipalEpoch } from '@/app/auth/principal-epoch';
import { api } from '@/shared/api/client';
import { surfacesKeys } from './surfaces.api';
import { failure, mockSurfaceReads, otherId, profileFixture, profileId, renderSurfaces, response, surfaceFixture, surfaceId } from './surfaces.test-support';

beforeAll(() => Object.defineProperty(window, 'matchMedia', { configurable: true, value: vi.fn(() => ({ matches: true, media: '', onchange: null, addEventListener: vi.fn(), removeEventListener: vi.fn(), addListener: vi.fn(), removeListener: vi.fn(), dispatchEvent: vi.fn() })) }));
afterEach(() => vi.restoreAllMocks());

describe('GEO Surface/Profile 管理闭环', () => {
  it('ENGINEER 直接访问两个详情只能读取摘要，无配置、设置、绑定或写操作', async () => {
    const surface = surfaceFixture({ configuration: null, available_actions: [], deletion: null, primary_task: 'VIEW_SUMMARY' });
    const profile = profileFixture({ configuration: null, available_actions: [], deletion: null, activation_blockers: null, primary_task: 'VIEW_SUMMARY' });
    mockSurfaceReads(() => surface, () => profile);
    const post = vi.spyOn(api, 'POST');
    const { router } = renderSurfaces(undefined, true);
    expect(await screen.findByText('当前为只读摘要。配置由管理员维护。')).toBeVisible();
    expect(screen.queryByRole('button', { name: /更多操作|新建观测面/ })).not.toBeInTheDocument();
    expect(screen.queryByRole('region', { name: '管理员非敏感配置' })).not.toBeInTheDocument();
    await act(() => router.navigate({ to: '/configuration/geo-surfaces', search: { tab: 'profiles', profile_id: profileId } }));
    expect(await screen.findByRole('region', { name: '采集配置详情' })).toBeVisible();
    expect(within(screen.getByRole('region', { name: '采集配置详情' })).getByText(/未测试（UNTESTED）/)).toBeVisible();
    expect(screen.queryByText('适配器')).not.toBeInTheDocument();
    expect(screen.queryByText('模型绑定')).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /更多操作|新建采集配置/ })).not.toBeInTheDocument();
    await act(() => router.navigate({ to: '/configuration/geo-surfaces', search: { tab: 'profiles', new: 1 } }));
    expect(await screen.findByText('当前账号没有创建 GEO 配置的权限。')).toBeVisible();
    expect(post).not.toHaveBeenCalled();
  });
  it('创建观测面采用 canonical 对象，保留最新 URL 筛选并携带完整非敏感 body', async () => {
    let current = surfaceFixture();
    mockSurfaceReads(() => current);
    const post = vi.spyOn(api, 'POST').mockImplementation(async () => { current = surfaceFixture({ summary: { ...current.summary, name: '本地观测面', slug: 'local-surface' }, configuration: { ...current.configuration!, name: '本地观测面', slug: 'local-surface' } }); return response(current); });
    const { router } = renderSurfaces('/configuration/geo-surfaces?new=1');
    const driver = userEvent.setup();
    await driver.type(await screen.findByRole('textbox', { name: '观测面名称' }), '本地观测面');
    await driver.type(screen.getByRole('textbox', { name: '观测面标识' }), 'local-surface');
    await driver.type(screen.getByRole('textbox', { name: '搜索配置名称' }), '最新筛选');
    await driver.click(screen.getByRole('button', { name: '应用搜索' }));
    await driver.click(screen.getByRole('button', { name: '创建观测面' }));
    await waitFor(() => expect(router.state.location.search.surface_id).toBe(surfaceId));
    expect(router.state.location.search.q).toBe('最新筛选');
    expect(router.state.location.search.new).toBeUndefined();
    expect(post).toHaveBeenCalledOnce();
    expect(post.mock.calls[0]).toMatchObject(['/api/v1/geo/engine-surfaces', { body: { name: '本地观测面', slug: 'local-surface', surface_kind: 'MANUAL_SITE', provider_brand: 'CUSTOM', website_url: null, compliance_status: 'NOT_REVIEWED', capabilities: { answer_text: true, citations: false, web_search_signal: false, model_version: false, usage: false, cost: false } }, params: { header: { 'X-CSRF-Token': 'surfaces-csrf' } } }]);
    expect(await screen.findByRole('form', { name: '编辑观测面' })).toBeVisible();
  });
  it('新建人工配置默认 inactive/UNTESTED，只提交人工闭合 settings，模式和所属编辑时冻结', async () => {
    mockSurfaceReads();
    const post = vi.spyOn(api, 'POST').mockResolvedValue(response(profileFixture()));
    renderSurfaces(`/configuration/geo-surfaces?tab=profiles&surface_id=${surfaceId}&new=1`);
    const driver = userEvent.setup();
    expect(await screen.findByRole('textbox', { name: '所属观测面 ID' })).toHaveValue(surfaceId);
    await driver.type(screen.getByRole('textbox', { name: '采集配置名称' }), '人工采集配置');
    await driver.click(screen.getByRole('button', { name: '创建采集配置' }));
    await waitFor(() => expect(post).toHaveBeenCalledOnce());
    expect(post.mock.calls[0]).toMatchObject(['/api/v1/geo/collection-profiles', { body: { collection_mode: 'MANUAL', adapter_key: 'manual', engine_surface_id: surfaceId, ai_channel_id: null, ai_model_id: null, login_state: 'ANONYMOUS', settings: { require_screenshot: true } } }]);
    const body = (post.mock.calls[0]?.[1] as unknown as { body: Record<string, unknown> }).body;
    expect(body).not.toHaveProperty('is_active'); expect(body).not.toHaveProperty('last_test_status');
    expect(await screen.findByRole('form', { name: '编辑采集配置' })).toBeVisible();
    expect(screen.queryByRole('textbox', { name: '所属观测面 ID' })).not.toBeInTheDocument();
    expect(screen.queryByRole('combobox', { name: '采集模式' })).not.toBeInTheDocument();
    expect(within(screen.getByRole('form', { name: '编辑采集配置' })).queryByRole('button', { name: /测试/ })).not.toBeInTheDocument();
  });
  it('后台刷新与任何 409 保留草稿；显式读取最新后用户再次提交才采用新 revision', async () => {
    let current = profileFixture();
    const get = mockSurfaceReads(undefined, () => current);
    const patch = vi.spyOn(api, 'PATCH').mockResolvedValueOnce(failure()).mockResolvedValueOnce(response(profileFixture({ summary: { ...current.summary, revision: 10, name: '本地名字' }, configuration: { ...current.configuration!, revision: 10, name: '本地名字' } })));
    const { queryClient } = renderSurfaces(`/configuration/geo-surfaces?tab=profiles&profile_id=${profileId}&editor=1`);
    const driver = userEvent.setup();
    await driver.clear(await screen.findByRole('textbox', { name: '采集配置名称' })); await driver.type(screen.getByRole('textbox', { name: '采集配置名称' }), '本地名字');
    await act(async () => { queryClient.setQueryData(surfacesKeys.profile(profileId), profileFixture({ summary: { ...current.summary, revision: 8, name: '后台名字' } })); });
    expect(screen.getByRole('textbox', { name: '采集配置名称' })).toHaveValue('本地名字');
    await driver.click(screen.getByRole('button', { name: '保存采集配置' }));
    expect(await screen.findByText(/surfaces-request-test/)).toBeVisible();
    expect(patch.mock.calls[0]?.[1]).toMatchObject({ body: { expected_revision: 7, name: '本地名字' } });
    expect(screen.getByRole('button', { name: '保存采集配置' })).toBeDisabled();
    current = profileFixture({ summary: { ...current.summary, revision: 9, name: '最新名字' }, configuration: { ...current.configuration!, revision: 9, name: '最新名字' } });
    await driver.click(screen.getByRole('button', { name: '加载最新版本并保留输入' }));
    await waitFor(() => expect(screen.getByRole('button', { name: '保存采集配置' })).toBeEnabled());
    expect(screen.getByRole('textbox', { name: '采集配置名称' })).toHaveValue('本地名字'); expect(patch).toHaveBeenCalledOnce();
    await driver.click(screen.getByRole('button', { name: '保存采集配置' }));
    await waitFor(() => expect(patch).toHaveBeenCalledTimes(2));
    expect(patch.mock.calls[1]?.[1]).toMatchObject({ body: { expected_revision: 9, name: '本地名字', collection_mode: 'MANUAL' } });
    expect((patch.mock.calls[1]?.[1] as unknown as { body: Record<string, unknown> }).body).not.toHaveProperty('engine_surface_id');
    expect(get.mock.calls.some((call) => call[0] === '/api/v1/geo/collection-profiles/{profile_id}')).toBe(true);
  });
  it('后台详情读取失败保持表单，并提供真实重试', async () => {
    const get = mockSurfaceReads();
    const { queryClient } = renderSurfaces(`/configuration/geo-surfaces?surface_id=${surfaceId}&editor=1`);
    const driver = userEvent.setup();
    await driver.type(await screen.findByRole('textbox', { name: '观测面名称' }), '草稿');
    get.mockResolvedValue(failure('SERVICE_UNAVAILABLE', 503));
    await act(async () => { await queryClient.refetchQueries({ queryKey: surfacesKeys.surface(surfaceId) }); });
    expect(await screen.findByText(/后台详情刷新失败/)).toBeVisible();
    expect(screen.getByRole('textbox', { name: '观测面名称' })).toHaveValue('测试观测面草稿');
    expect(screen.getByRole('button', { name: '重试详情刷新' })).toBeVisible();
  });
  it('保存会取消正在读取的详情；忽略取消的旧 GET 也不能覆盖 canonical 保存结果', async () => {
    const get = mockSurfaceReads();
    const canonical = surfaceFixture({ summary: { ...surfaceFixture().summary, revision: 9, name: '保存后名称' }, configuration: { ...surfaceFixture().configuration!, revision: 9, name: '保存后名称' } });
    const patch = vi.spyOn(api, 'PATCH').mockResolvedValue(response(canonical));
    const { queryClient } = renderSurfaces(`/configuration/geo-surfaces?surface_id=${surfaceId}&editor=1`);
    const driver = userEvent.setup();
    await driver.type(await screen.findByRole('textbox', { name: '观测面名称' }), '草稿');
    let release!: (value: never) => void;
    let signal: AbortSignal | undefined;
    get.mockImplementation(async (path, options) => {
      if (path === '/api/v1/geo/engine-surfaces/{surface_id}') {
        signal = (options as unknown as { signal?: AbortSignal })?.signal;
        return new Promise((resolve) => { release = resolve; });
      }
      return response({ items: [canonical], page: 1, page_size: 20, total: 1 });
    });
    await act(async () => { void queryClient.refetchQueries({ queryKey: surfacesKeys.surface(surfaceId) }); });
    await waitFor(() => expect(signal).toBeDefined());
    await driver.click(screen.getByRole('button', { name: '保存观测面' }));
    await waitFor(() => expect(queryClient.getQueryData<ReturnType<typeof surfaceFixture>>(surfacesKeys.surface(surfaceId))?.summary.revision).toBe(9));
    expect(signal?.aborted).toBe(true);
    await act(async () => release(response(surfaceFixture())));
    expect(queryClient.getQueryData<ReturnType<typeof surfaceFixture>>(surfacesKeys.surface(surfaceId))?.summary.revision).toBe(9);
    expect(screen.getByRole('textbox', { name: '观测面名称' })).toHaveValue('保存后名称');
    expect(patch).toHaveBeenCalledOnce();
  });
  it('服务端字段失败保留输入，标记字段并可从错误摘要聚焦', async () => {
    mockSurfaceReads();
    const envelope = { error: { code: 'VALIDATION_ERROR', message: '名称不可用', request_id: 'surfaces-field-error', details: { errors: [{ loc: ['body', 'name'], msg: '请使用其他名称', type: 'value_error' }] } } };
    vi.spyOn(api, 'PATCH').mockResolvedValue({ error: envelope, response: Response.json(envelope, { status: 422 }) } as never);
    renderSurfaces(`/configuration/geo-surfaces?surface_id=${surfaceId}&editor=1`);
    const driver = userEvent.setup();
    await driver.type(await screen.findByRole('textbox', { name: '观测面名称' }), '草稿');
    await driver.click(screen.getByRole('button', { name: '保存观测面' }));
    const summary = await screen.findByRole('link', { name: '请使用其他名称' });
    const input = screen.getByRole('textbox', { name: '观测面名称' });
    expect(input).toHaveValue('测试观测面草稿');
    expect(input).toHaveAttribute('aria-invalid', 'true');
    await driver.click(summary);
    expect(input).toHaveFocus();
    expect(screen.getByText(/surfaces-field-error/)).toBeVisible();
  });
  it('dirty 草稿阻断关闭、切换资源和 Tab；筛选更新不卸载草稿', async () => {
    mockSurfaceReads();
    const { router } = renderSurfaces(`/configuration/geo-surfaces?surface_id=${surfaceId}&editor=1`);
    const driver = userEvent.setup();
    await driver.type(await screen.findByRole('textbox', { name: '观测面名称' }), '草稿');
    await driver.type(screen.getByRole('textbox', { name: '搜索配置名称' }), '新的过滤'); await driver.click(screen.getByRole('button', { name: '应用搜索' }));
    await waitFor(() => expect(router.state.location.search.q).toBe('新的过滤'));
    await driver.click(screen.getByRole('button', { name: '关闭编辑' }));
    let dialog = await screen.findByRole('dialog', { name: '要离开当前页面吗？' });
    await driver.click(within(dialog).getByRole('button', { name: '继续编辑' }));
    expect(screen.getByRole('textbox', { name: '观测面名称' })).toHaveValue('测试观测面草稿');
    await driver.click(screen.getByRole('tab', { name: '采集配置' }));
    dialog = await screen.findByRole('dialog', { name: '要离开当前页面吗？' });
    await driver.click(within(dialog).getByRole('button', { name: '放弃修改并离开' }));
    await waitFor(() => expect(router.state.location.search.tab).toBe('profiles'));
    expect(screen.queryByRole('form', { name: '编辑观测面' })).not.toBeInTheDocument();
  });
  it('主体 epoch 改变后，延迟保存不写 cache 或导航', async () => {
    mockSurfaceReads();
    let resolve!: (result: never) => void;
    const patch = vi.spyOn(api, 'PATCH').mockImplementation(() => new Promise((done) => { resolve = done; }));
    const { queryClient } = renderSurfaces(`/configuration/geo-surfaces?surface_id=${surfaceId}&editor=1`);
    const driver = userEvent.setup();
    await driver.type(await screen.findByRole('textbox', { name: '观测面名称' }), '草稿'); await driver.click(screen.getByRole('button', { name: '保存观测面' }));
    await waitFor(() => expect(patch).toHaveBeenCalledOnce());
    await act(async () => { advancePrincipalEpoch(queryClient, 'new-principal'); resolve(response(surfaceFixture({ summary: { ...surfaceFixture().summary, revision: 90 } }))); });
    expect(queryClient.getQueryData<ReturnType<typeof surfaceFixture>>(surfacesKeys.surface(surfaceId))?.summary.revision).toBe(4);
    expect(screen.queryByText('已保存当前配置。')).not.toBeInTheDocument();
  });
  it('卸载或切换编辑身份后，旧保存不会污染新资源', async () => {
    mockSurfaceReads();
    let resolve!: (result: never) => void;
    const patch = vi.spyOn(api, 'PATCH').mockImplementation(() => new Promise((done) => { resolve = done; }));
    const { router, queryClient } = renderSurfaces(`/configuration/geo-surfaces?surface_id=${surfaceId}&editor=1`);
    await screen.findByRole('form', { name: '编辑观测面' });
    fireEvent.submit(screen.getByRole('form', { name: '编辑观测面' }));
    await waitFor(() => expect(patch).toHaveBeenCalledOnce());
    await act(() => router.navigate({ to: '/configuration/geo-surfaces', search: { surface_id: otherId }, ignoreBlocker: true }));
    await act(async () => resolve(response(surfaceFixture({ summary: { ...surfaceFixture().summary, revision: 90 } }))));
    expect(queryClient.getQueryData<ReturnType<typeof surfaceFixture>>(surfacesKeys.surface(surfaceId))?.summary.revision).toBe(4);
    expect(router.state.location.search.surface_id).toBe(otherId);
  });
  it('Surface 编辑入口由 UPDATE token 决定，相同状态没有 UPDATE 时无编辑按钮', async () => {
    mockSurfaceReads(() => surfaceFixture({ available_actions: [], primary_task: 'ENABLE_SURFACE' }));
    renderSurfaces();
    expect(await screen.findByRole('button', { name: '查看并启用' })).toBeVisible();
    expect(screen.queryByRole('button', { name: '更多操作：测试观测面' })).not.toBeInTheDocument();
    expect(screen.queryByRole('form', { name: '编辑观测面' })).not.toBeInTheDocument();
  });
  it.each([403, 404])('直接访问详情 HTTP %s 显式失败并保留 request ID', async (status) => {
    vi.spyOn(api, 'GET').mockImplementation(async (path) => path === '/api/v1/geo/engine-surfaces' ? response({ items: [], page: 1, page_size: 20, total: 0 }) : failure(status === 403 ? 'FORBIDDEN' : 'NOT_FOUND', status));
    renderSurfaces();
    expect(await screen.findByText(/surfaces-request-test/)).toBeVisible();
    expect(screen.queryByRole('region', { name: '观测面详情' })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: '关闭详情' })).toBeVisible();
  });
});
